### PR TITLE
Fix !include tag loading 

### PR DESCRIPTION
**Pull request by FabioRosado**
# Description

Using #1114 branch to see if travis will run

## Status
**READY** | **UNDER DEVELOPMENT** | **ON HOLD**

## Type of change

_Please delete options that are not relevant._

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
- Documentation (fix or adds documentation)

# How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration._

- Test A
- Test B

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by MrNaif2018** [comment]
I am not sure why is this needed, isn't my pr working fine? If you change CSafeLoader to SafeLoader it won't always work as yamale uses exactly the same code as from my pr.

**Comment by FabioRosado** [comment]
@MrNaif2018 that change is related to the tests and if you check this commit history I am using your commits, the reason why I raised this PR with your history is because travis is not run on your own PR.

I've just been trying to bump the coverage for that try/except bit on the code, feel free to add this to your PR and i'll pull it from there.

Note that you will get all the credit from the work (both for hacktoberfest and opsdroid stickers)

**Comment by MrNaif2018** [comment]
Ah, fine. Will check coverage issues later unless you fix it before me :D

**Comment by FabioRosado** [comment]
Yeah I was going to comment on your PR the reason why I opened this one but then I got stuck with tests and real life haha

But yeah Travis acted funny that's why this PR is open 😄 👍 

I'll leave the coverage issue to you since I haven't figure out how to test it, if you are unable to sort it out I'm sure a dip on the loader.py is still okay since the overall coverage got bumped by 0.08%

**Comment by MrNaif2018** [comment]
Well this AttributeError is raised when system yaml library(or pyyaml C extension) isn't available, then it falls back to default loader. Will try it more tomorrow(oh, today already :D)

**Pull request closed without merging**
