### PR TITLE
Switch arg parsing to click and add version flag

### LINKED ISSUE #514: Switch CLI to use click
I recently discovered [`click`](http://click.pocoo.org/5/) which makes adding command line options and arguments to your python application super simple and much more robust.

We should look at replacing the [current argparse code](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/__main__.py#L88) with `click`!

### PR DESCRIPTION
**Pull request by jacobtomlinson**
# Description

Switches the argument parsing to use [click](http://click.pocoo.org/5/). 

Click makes handing command line flags easier and also prints useful help messages via the `--help` flag. (When installed with pip it should say `opsdroid` instead of `__main__.py`).

```
$ python -m opsdroid --help
Usage: __main__.py [OPTIONS]

  Opsdroid is chat bot framework written in python.

  It is designed to be extendable, scalable and simple. See
  https://opsdroid.github.io/ for more information.

Options:
  --gen-config   Print an example config and exit.
  -v, --version  Print the version and exit.
  --help         Show this message and exit.
```

I've moved the `--gen-config` command over to click which means removing the logic which checks for the flag and adding a decorator which eagerly runs a callback. The `print_example_config` function has been updated to conform to the click callback format.

I have also added another decorator similar to `--gen-config` called `--version` which simply prints out the current opsdroid version and then exits, similar to gen config printing the example config and exiting.

Closes #514

## Status
**READY**

## Type of change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- Run the test suite

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
@FabioRosado could you review this?

**Comment by FabioRosado** [comment]
I like how you added those flag so we can see the version number. 

Should we perhaps add in documentation this flags just so people can use them after reading the documentation?

**Comment by jacobtomlinson** [comment]
Done @FabioRosado! Merge when you're happy!

**Comment by FabioRosado** [comment]
I've edited the readme and the main just to add a missing "a" in "Opsdroid is chat bot framework written in Python."

I had to use the github browser to edit the files that's why the two commits are being shown (I have no idea how to edit these commits from my cli) will merge as soon as the tests show green 😄

**Pull request merged**
