### PR TITLE
Add in capability to supply `user` and `password` with mongodb

### PR DESCRIPTION
**Pull request by ajitdsa**
# Description

Some mongodb environments require `user` and `password` to be supplied in order to properly connect. This change allows this while not breaking current functionality where this does not need to be provided.

Add documentation to support `user` and `password` functionality for mongodb.

## Status
**READY**

## Type of change

- New feature (non-breaking change which adds functionality)
- Documentation (fix or adds documentation)

# How Has This Been Tested?

- Manually connected to mongodb that required user/password to be set _without_ the params set up in my configuration file to make sure that failed.
- Manually connected to mongodb that required user/password to be set _with_ the params set up in my configuration file to make sure that failed.
- Ran existing tests to make sure current connect functionality still ran.
- Added a new test that passed in `user` and `password` when initializing the database

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation (if applicable)
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Cadair — APPROVED** [review]
Seems sane.

**Review by jacobtomlinson — CHANGES_REQUESTED** [review]
This looks great, thank you so much. 

Could I ask you to also update the config schema?

https://github.com/opsdroid/opsdroid/blob/021aa68685ee18921716445106b889c37b6d0b3b/opsdroid/database/mongo/__init__.py#L10

**Comment by ajitdsa** [comment]
> This looks great, thank you so much.
> 
> Could I ask you to also update the config schema?
> 
> https://github.com/opsdroid/opsdroid/blob/021aa68685ee18921716445106b889c37b6d0b3b/opsdroid/database/mongo/__init__.py#L10

@jacobtomlinson Done!

**Review by jacobtomlinson — APPROVED** [review]

**Comment by jacobtomlinson** [comment]
Awesome work thanks @ajitdsa

**Pull request merged**
