### PR TITLE
Translation to Spanish

### PR DESCRIPTION
**Pull request by jorrgme**
Added some translations to Spanish for opsdroid

### CODE REVIEW

**Comment by jorrgme** [comment]
Yeah it's a typo, I'll fix it in a second

**Comment by FabioRosado** [comment]
Awesome! Thank you so much for taking the time to work on this. As soon as travis finishes I’ll merge this PR 👍

**Comment by jorrgme** [comment]
Thanks to you! I'll try to include more translations when i have the time 😄

**Comment by jacobtomlinson** [comment]
Ping me your address via DM on [Twitter](https://twitter.com/_jacobtomlinson) or [Gitter](https://gitter.im/opsdroid) and I'll post you some [opsdroid stickers](https://medium.com/opsdroid/stickers-for-contributors-a0a1f9c30ec1)!

**Pull request merged**
