### PR TITLE
Update contributing.md

### PR DESCRIPTION
**Pull request by sakshamtaneja21**
# Description
create typo
_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change._

Fixes #<issue>

## Status
**READY** | **UNDER DEVELOPMENT** | **ON HOLD**

## Type of change

_Please delete options that are not relevant._

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
- Documentation (fix or adds documentation)

# How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration._

- Test A
- Test B

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
I'm going to merge this as the changes make things very slightly better than they were before. But I'm marking as **invalid** hacktoberfest spam for the following reasons:

- Does not solve an open issue.
- Low effort contribution. 

_Be careful as the [Hacktoberfest team may disqualify you](https://hacktoberfest.digitalocean.com/faq#general) for making low quality contributions._

**Comment by sakshamtaneja21** [comment]
so i will try my best for more contribution

**Comment by sakshamtaneja21** [comment]
please make it valid

**Comment by sakshamtaneja21** [comment]
thanks

**Comment by sakshamtaneja21** [comment]
how can I get an invite of your GitHub organization as a member

**Comment by FabioRosado** [comment]
Please stop spamming closed issues. Opsdroid organization is only for maintainers of the project and for someone to be considered to be a maintainer that person needs to contribute to the project for a long time and with useful PR's.

**Pull request merged**
