### PR TITLE
Try pip3 if pip is not found

### PR DESCRIPTION
**Pull request by FabioRosado**
# Description

Opsdroid runs smoothly again when the try/except is added to the loader.
I would like a feedback on the test if possible, I'm not sure if I'm testing it properly or not.

**Fixes** #385

## Status
**READY** | ~~**UNDER DEVELOPMENT**~~ | ~~**ON HOLD**~~

## Type of change

_Please delete options that are not relevant._

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration._

- Tox - tests passed
- Travis - Tests failed

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
#388 should resolve the CI issues you were having. I've updated your branch to include the new library.

**Comment by jacobtomlinson** [comment]
Great Travis has passed now.

**Comment by FabioRosado** [comment]
Thanks for the help jacob, I wasn't sure how to implements you suggested fully the first time 👍 
It seems that the test I created for the except raise isn't covering it for some reason, I'll try to play around with it and see if I can fix the issue

**Comment by jacobtomlinson** [comment]
Thinking about it we might want to raise an exception and exit instead of `return False` because if deps fails to install you can be reasonably sure opsdroid will not function correctly.

At the very least it probably needs to log an error saying it can't find pip.

**Comment by FabioRosado** [comment]
Is this the general function for any required installs for opsdroid? If this is just used to install requirements for skill/connectors it shouldn't be too bad, the skill would just not work I guess?

If its used to install everything then yeah I get it might be a problem

**Comment by jacobtomlinson** [comment]
It's for module dependency installs, so connectors, databases and skills.

**Comment by jacobtomlinson** [comment]
Looking good. Needs a test for both exceptions. Just needs a side effect on `subprocess.Popen` to raise the `FileNotFoundError` and the test should assert that it raises the overall error.

Also when raising if both pip installs fail perhaps it should be an `OSError` or a `RuntimeError` instead of a `FileNotFoundError`.

**Comment by FabioRosado** [comment]
I was just writing in gitter. I'm thinking in giving this a try:
```python
```
    def test_no_pip_install(self):
        opsdroid, loader = self.setup()
        with mock.patch.object(subprocess, 'Popen') as mocked_popen:
            mocked_popen.side_effect = FileNotFoundError()
            self.assertRaises(FileNotFoundError, mocked_popen)
            with mock.patch.object(loader, 'pip_install_deps') as pip_install:
                mocked_popen.return_value.\
                    communicate.return_value = ['Test\nTest']
                loader.pip_install_deps("/path/to/some/file.txt")
                self.assertTrue(pip_install.called)
```

The way I think about it is that: popen raises the exception. Then it tries again and returns the right value (with pip3 I guess) and then it all passes. The code works on my end but just wanted to check with you. 

I was unsure which exception to raise, I'll change it with OSError one instead.

**Comment by FabioRosado** [comment]
Hmm... okay that change in the tests didn't work

**Comment by jacobtomlinson** [comment]
I find it easier to use `self.assertRaises` in a with statement. That might help.

You've also patched `with mock.patch.object(loader, 'pip_install_deps')` further down which means your `mocked_popen` wont get called at all within that block.

**Comment by FabioRosado** [comment]
Oh wow... I have to say that I didn't expect this tests to pass but.... hey, they did! 
I would still love to get some feedback from you @jacobtomlinson just to know if you would test this try/except block differently.

Thanks 👍

**Comment by jacobtomlinson** [comment]
This looks great! The only comment I have is that you don't need the OSError side effect in the test. The code will already be raising that error. You should be able to just remove that from the array and it's ready to be merged.

**Pull request merged**
