### PR TITLE
opsdroid documents translation(Korean)

### PR DESCRIPTION
**Pull request by JYH0817**
Translated configuration, exposing, some connectors and examples

### CODE REVIEW

**Review by jacobtomlinson — COMMENTED** [review]
Wow thanks for this.

Sadly it looks like the docs builds are failing due to unknown characters. Do you have experience being SPhinx sites with multiple languages and supporting Korean?

**Comment by JYH0817** [comment]
> Wow thanks for this.
> 
> Sadly it looks like the docs builds are failing due to unknown characters. Do you have experience being SPhinx sites with multiple languages and supporting Korean?

I don't have experience about that... but I'll try to fix that

**Comment by JYH0817** [comment]
> > Wow thanks for this.
> > Sadly it looks like the docs builds are failing due to unknown characters. Do you have experience being SPhinx sites with multiple languages and supporting Korean?
> 
> I don't have experience about that... but I'll try to find the problem



> Wow thanks for this.
> 
> Sadly it looks like the docs builds are failing due to unknown characters. Do you have experience being SPhinx sites with multiple languages and supporting Korean?

I think UTF-8 option will be needed in SPhinx conf file

**Comment by jacobtomlinson** [comment]
> I don't have experience about that... but I'll try to find the problem

I'm not entirely sure how to accept this change. I think these translations will go out of date quickly. I also have no experience building sphinx sites in multiple languages.

**Comment by JYH0817** [comment]
> > I don't have experience about that... but I'll try to find the problem
> 
> I'm not entirely sure how to accept this change. I think these translations will go out of date quickly. I also have no experience building sphinx sites in multiple languages.

Idk if they will help you

https://github.com/julot/sphinxcontrib-cjk
https://github.com/hanpama/docker-texlive-korean

**Comment by jacobtomlinson** [comment]
Ok thanks. Do you have any thoughts on how we can keep this up to date going forwards? I just don't feel like this is going to be sustainable.

**Comment by JYH0817** [comment]
> Ok thanks. Do you have any thoughts on how we can keep this up to date going forwards? I just don't feel like this is going to be sustainable.

I will re-translate docs if original docs are updated, and I will translate more docs

**Comment by jacobtomlinson** [comment]
That is a very big commitment. Do you intend to track every Pull Request that we get in Opsdroid and add translations for all docs changes that get made?

**Comment by JYH0817** [comment]
> That is a very big commitment. Do you intend to track every Pull Request that we get in Opsdroid and add translations for all docs changes that get made?

I'll try my best when I have free time

**Pull request closed without merging**
