### PR TITLE
Fixing rasanlu parser does not manage the new returned response after training request 

### LINKED ISSUE #886: rasanlu parser does not manage the new returned response after training request
# Description

This issue was initially detected by @jhofeditz when testing the fix #881.
The new rasanlu trainer instead of returning a json response after a model training, it return a zip file with all files generated by the trainer.

## Steps to Reproduce
1- Download docker image rasa/rasa_nlu:latest-spacy
2- Start docker image
3- Use a skill that interact with rasanlu and that need rasa to be trained using an intents.yml file
4- activate the skill in your opsdroid config file
5- Start opsdroid 

## Expected Functionality
Opsdroid should be capable to manage json response and zip response

## Experienced Functionality

Crash of opsdroid due to parsing error

## Versions
- **Opsdroid version: v0.14.1+37.ge71ea43**
- **Rasanlu version: 0.15.0a1**
- **Python version: 3.7.2**
- **OS/Docker version: Docker version 18.09.2, build 6247962 **

## Additional Details

**From Rasa side :**
```
2019-03-30 11:37:34 INFO     rasa_nlu.data_router  - Logging of requests is disabled. (No 'request_log' directory configured)
2019-03-30 11:37:34 INFO     __main__  - Started http server on port 5000
2019-03-30 11:37:34+0000 [-] Log opened.
2019-03-30 11:37:34+0000 [-] Site starting on 5000
2019-03-30 11:37:34+0000 [-] Starting factory <twisted.web.server.Site object at 0x7f65ffbff470>
2019-03-30 11:50:43+0000 [-] 2019-03-30 11:50:43 DEBUG    rasa_nlu.data_router  - New training queued
Fitting 2 folds for each of 6 candidates, totalling 12 fits
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  12 out of  12 | elapsed:    0.0s finished
2019-03-30 11:50:59+0000 [-] "172.17.0.1" - - [30/Mar/2019:11:50:58 +0000] "POST /train?project=ergo&fixed_model_name=1c0badaf3eb8c2bf6546465eadfd8492e7d79c1f0f3520d103d4bc39b4bfc&token=sfgz654zfg546qs4fg646rg64efg HTTP/1.1" 200 11767 "-" "Python/3.7 aiohttp/3.5.4"
2019-03-30 11:53:24+0000 [-] "172.17.0.1" - - [30/Mar/2019:11:53:23 +0000] "GET / HTTP/1.1" 200 29 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:65.0) Gecko/20100101 Firefox/65.0"
2019-03-30 11:53:24+0000 [-] "172.17.0.1" - - [30/Mar/2019:11:53:23 +0000] "GET /favicon.ico HTTP/1.1" 404 233 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:65.0) Gecko/20100101 Firefox/65.0"
2019-03-30 11:54:24+0000 [-] Timing out client: IPv4Address(type='TCP', host='172.17.0.1', port=59948)
```

**From Opsdroid side :**
```
INFO opsdroid.parsers.rasanlu: Starting Rasa NLU training.
INFO opsdroid.parsers.rasanlu: Now training the model. This may take a while...
DEBUG asyncio: Using selector: KqueueSelector
Traceback (most recent call last):
...
  File "/Users/hicham/Developments/Bots/opsdroid-iobreaker/opsdroid/opsdroid/parsers/rasanlu.py", line 117, in train_rasanlu
    result = await resp.json()
  File "/Users/hicham/.virtualenvs/opsdroid/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1027, in json
    headers=self.headers)
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: application/zip'
```

### PR DESCRIPTION
**Pull request by iobreaker**
# Description

This issue was initially detected by @jhofeditz when testing the fix #881.
The new rasanlu trainer instead of returning a json response after a model training, it return a zip file with all files generated by the trainer.

Fixes #886 

Check if rasanlu response is **application/json** or **application/zip**, if it's a zip file and if the **content_disposition** indicate a file attachment.

After a discussion with @jacobtomlinson (see issue history) we decided to ignore the returned zip file for the moment. if needed the code can be updated to handle it differently (saving the file in a directory for example)

## Status
**READY** | **~~UNDER DEVELOPMENT~~** | **~~ON HOLD~~**

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

I tested the fix on my environment, no issue detected

- **Test  : Using Docker opsdroid version**  

```

opsdroid ❯ python -m opsdroid
INFO opsdroid.logging: ========================================
INFO opsdroid.logging: Started opsdroid v0.15.4+24.g7ec3d7e.dirty
DEBUG asyncio: Using selector: KqueueSelector
DEBUG opsdroid.loader: Loaded loader
DEBUG opsdroid.loader: Loading modules from config...
WARNING opsdroid.loader: No databases in configuration.This will cause skills which store things in memory to lose data when opsdroid is restarted.
DEBUG opsdroid.loader: Loading skill modules...
DEBUG opsdroid.loader: 'no-cache' set, removing /Users/hicham/Library/Application Support/opsdroid/opsdroid-modules/skill/social
DEBUG opsdroid.loader: Installing social...
DEBUG opsdroid.loader: Installed social to /Users/hicham/Library/Application Support/opsdroid/opsdroid-modules/skill/social
DEBUG opsdroid.loader: Couldn't find the file requirements.txt, skipping.
DEBUG opsdroid.loader: Loaded skill: opsdroid-modules.skill.social
DEBUG opsdroid.loader: Loading connector modules...
DEBUG opsdroid.loader: Loaded connector: opsdroid.connector.websocket
DEBUG opsdroid.loader: Loaded connector: opsdroid.connector.telegram
DEBUG opsdroid.core: Loaded 1 skills
INFO opsdroid.parsers.rasanlu: Starting Rasa NLU training.
INFO opsdroid.parsers.rasanlu: Now training the model. This may take a while...
INFO opsdroid.parsers.rasanlu: Rasa NLU training completed in 15 seconds.
INFO opsdroid.parsers.rasanlu: Initialising Rasa NLU model.
DEBUG opsdroid.parsers.rasanlu: Rasa NLU response - {"intent": {"name": null, "confidence": 0.0}, "entities": [], "text": "", "project": "ibot", "model": "model_20190609-114156"}
INFO opsdroid.parsers.rasanlu: Initialisation complete in 14 seconds.
DEBUG opsdroid.parsers.rasanlu: =========> returned model file saved to : /Users/hicham/Desktop/model.zip
DEBUG opsdroid.connector.websocket: Starting Websocket connector
DEBUG opsdroid.connector.telegram: Loaded telegram connector
DEBUG opsdroid.connector.telegram: Connecting to telegram
DEBUG opsdroid.connector.telegram: {'ok': True, 'result': {'id': 731324986, 'is_bot': True, 'first_name': 'ChamixLocalBot', 'username': 'ChamixLocalBot'}}
DEBUG opsdroid.connector.telegram: Connected to telegram as ChamixLocalBot
INFO opsdroid.core: Opsdroid is now running, press ctrl+c to exit.
INFO opsdroid.web: Started web server on http://0.0.0.0:8080
```

No more crash

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by iobreaker** [comment]
Humm, Any idea ?

```
lint run-test-pre: PYTHONHASHSEED='1477368579'
lint run-test: commands[0] | flake8 --builtins=_ opsdroid
lint run-test: commands[1] | pydocstyle opsdroid tests
lint run-test: commands[2] | black --check opsdroid tests scripts setup.py versioneer.py
would reformat /home/travis/build/opsdroid/opsdroid/opsdroid/parsers/rasanlu.py
would reformat /home/travis/build/opsdroid/opsdroid/tests/test_parser_rasanlu.py
All done! 💥 💔 💥
2 files would be reformatted, 84 files would be left unchanged.
ERROR: InvocationError for command /home/travis/build/opsdroid/opsdroid/.tox/lint/bin/black --check opsdroid tests scripts setup.py versioneer.py (exited with code 1)
```

**Comment by iobreaker** [comment]
ok got it

```
# /Users/hicham/Developments/Bots/opsdroid-iobreaker/opsdroid/.tox/lint/bin/black tests                                                                                                                       
reformatted /Users/hicham/Developments/Bots/opsdroid-iobreaker/opsdroid/tests/test_parser_rasanlu.py
All done! ✨ 🍰 ✨
1 file reformatted, 39 files left unchanged.
```

**Comment by iobreaker** [comment]
@jacobtomlinson as promised the PR was created.
Can you please check for the codecov part
Thanks

**Comment by jacobtomlinson** [comment]
I wonder if this is a problem with the test getting so long. The test first sets the return code to `404` and checks some things, then it updates it to `200` and checks some other things. However the coverage shows that the code path with `200` isn't being followed.

I think a good first step would be to break it up into separate tests. That way we can narrow down where the problem is. 

It's slightly confusing because the tests are passing.

**Comment by iobreaker** [comment]
I splitted the test into two tests but still not working

```python
    async def test_train_rasanlu_succeeded(self):
        result = amock.Mock()
        result.status = 200
        result.json.return_value = {"info": "new model trained: abc1230"}
        result.text = {"info": "new model trained: abc123"}
        result.content_type = 'application/json'

        with amock.patch(
            "aiohttp.ClientSession.post"
        ) as patched_request, amock.patch.object(
            rasanlu, "_get_all_intents"
        ) as mock_gai, amock.patch.object(
            rasanlu, "_init_model"
        ) as mock_im, amock.patch.object(
            rasanlu, "_build_training_url"
        ) as mock_btu, amock.patch.object(
            rasanlu, "_get_existing_models"
        ) as mock_gem, amock.patch.object(
            rasanlu, "_get_intents_fingerprint"
        ) as mock_gif:


            mock_gem.return_value = ["abc123"]
            mock_btu.return_value = "http://example.com"
            mock_gai.return_value = "Hello World"
            mock_gif.return_value = "abc123"

            patched_request.side_effect = None
            print("----> result : " + str(vars(result)))
            print("")
            print("----> result.json : " + str(vars(result.json)))
            print("")
            patched_request.return_value.set_result(result)
            print("----> patched_request : " + str(vars(patched_request)))
            print("")
            print("----> patched_request.json : " + str(vars(patched_request.json)))
            self.assertEqual(await rasanlu.train_rasanlu({}, {}), True)
```

Tox test

``
tox -e py36  tests/test_parser_rasanlu.py::TestParserRasaNLU                                                                                                                                                ...
py36 run-test-pre: PYTHONHASHSEED='1336707378'
py36 runtests: commands[0] | py.test -v --timeout=30 --cov=opsdroid --cov-report term-missing:skip-covered --cov-report=xml:cov.xml tests/test_parser_rasanlu.py::TestParserRasaNLU
================ test session starts ================
platform darwin -- Python 3.6.5, pytest-4.6.2, py-1.8.0, pluggy-0.12.0 -- /Users/hicham/Developments/Bots/opsdroid-iobreaker/opsdroid/.tox/py36/bin/python
cachedir: .tox/py36/.pytest_cache
rootdir: /Users/hicham/Developments/Bots/opsdroid-iobreaker/opsdroid, inifile: setup.cfg
plugins: timeout-1.3.3, cov-2.7.1
timeout: 30.0s
timeout method: signal
timeout func_only: False
collected 21 items

...
tests/test_parser_rasanlu.py::TestParserRasaNLU::test_train_rasanlu_fails PASSED                                                                                                                                                                                   [ 95%]
tests/test_parser_rasanlu.py::TestParserRasaNLU::test_train_rasanlu_succeeded PASSED                                                                                                                                                                               [100%]

---------- coverage: platform darwin, python 3.6.5-final-0 -----------
Name                                         Stmts   Miss  Cover   Missing
--------------------------------------------------------------------------
...
opsdroid/parsers/rasanlu.py                    127     13    90%   117-150
...
--------------------------------------------------------------------------
TOTAL                                         2396   1828    24%

3 files skipped due to complete coverage.
Coverage XML written to file cov.xml

=============== 21 passed in 1.47 seconds ===================
______________ summary _______________________
  py36: commands succeeded
  congratulations :)
```

The strange thing is even if i changed the status to 404 it's marked as passed !!!!

**Comment by iobreaker** [comment]
Finally after 1 week trying to understand why coverage is not 100%  

```
  py36: commands succeeded
  py37: commands succeeded
  lint: commands succeeded
```

:-)

**Pull request merged**
