### PR TITLE
Add script for updating skill section in example configuration

### PR DESCRIPTION
**Pull request by vitkhab**
# Description
Script to update example_configuration.yaml based on available skills.

**Fixes:** #214 

## Status
**UNDER DEVELOPMENT**

## Type of change
New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Manual test
```python3 scripts/update_example_config.py```
Run command inside repo directory and look to changes made to `example_configuration.yaml` file

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
This looks exciting! I'm eager to see when it's done.

The build is failing due to your script not adhering to [PEP 8](https://www.python.org/dev/peps/pep-0008/).

**Comment by jacobtomlinson** [comment]
Has this gone stale?

**Comment by vitkhab** [comment]
@jacobtomlinson no, but my main job consumes a lot of time. I'm working on this in background

**Comment by vitkhab** [comment]
@jacobtomlinson I tried new approach with template because I thought it won't be reliable to parse existing config (any change could broke the script). How is it?
Where should I put new files: template and script requirements? Is it ok to be in scripts directory?
Are there any other considerations?

I'll think a little more about variable and function naming and try to use more informative naming. Also I'll think about script testing. Or is it overkill?

**Comment by jacobtomlinson** [comment]
Thanks for working on this!

Thoughts:
- Adding dependancies to the core project for a script to be used by maintainers isn't ideal. Perhaps we should create a `requirements_dev.txt` for these and update the contributor docs to reflect that?
- Yes I think the `scripts` directory is a good place, however perhaps it should go in a subdirectory so it's obvious that `configuration.j2` belongs to your script.
- I would probably say testing is overkill as it's only for contributor use.
- The code looks pretty readable, but some docstrings might help.

**Comment by jacobtomlinson** [comment]
@vitkhab Any chance you can take a look at the couple of points I made a few weeks ago. Would be great to get this in.

**Comment by jacobtomlinson** [comment]
Replaced by #370

**Pull request closed without merging**
