### PR TITLE
add a parser using parse lib (proposal)

### PR DESCRIPTION
**Pull request by anxodio**
# Description

I was reading the issue #447, thinking about the code in:
```python
@match_regex('my name is (?P<name>\w+) and my wife is called (?P<wife>\w+) and my son is called (?P<son>\w+)')
async def my_name_is(opsdroid, config, message):
    name = message.regex.group('name')
    wife = message.regex.group('wife')
    son = message.regex.group('son')
```
I thought that that's very "complicated" for just get some parameters. Regex it's very powerful and flexible, but for easy cases like this it's an overhead.

That's the reason why I make this proposal aiming to add a new core parser using [parse](https://github.com/r1chardj0n3s/parse) python lib.

It simplify a lot that type of matchers, using the classic format python style. For example, the example above will become:
```python
@match_parse('my name is {name} and my wife is called {wife} and my son is called {son}')
async def my_name_is(opsdroid, config, message):
    name = message.parse_result['name']
    wife = message.parse_result['wife']
    son = message.parse_result['son']
```

It can be very useful for easy matches, and can help to developers with few regex skills.

What do you think? If you like it, I will finish the implementation with tests and doc 😄 

## Status
**UNDER DEVELOPMENT**

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update
- Documentation (fix or adds documentation)

# How Has This Been Tested?

It must be tested if we find it interesting.

# Checklist:

- [X] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Love it! Please continue. 

This would be perfect for getting started with opsdroid.

**Comment by anxodio** [comment]
I'm thinking about the score... I don't know how to calculate it. I don't understand the approach used in regex :/

My point is that you use something like:
```python
@match_parse('hello')
@match_parse('hello {name}, how are you?')
``` 
And parse resolve it, probably it's a 100% score. But the problem can be:
```python
@match_parse('hello {name}')
```
In this case, name will parse all things until the end of the sentence. It will match `hello Jacob`, but it will match `hello Jacob, how are you` too (setting `name=Jacob, how are you`).
So use here a 100% score its a bad thing.

Any troughs?

**Comment by jacobtomlinson** [comment]
Sorry for the delay! This is a tricky one so I'll try and explain my thinking here, I'm really keen to get feedback too.

In the case where multiple skills match a message only the most certain match is used. All NLU APIs provide a certainty score for the matches. This means that skills can have numerous matchers on them and depending on the configuration only some of them will be used, but in the case where two match the skill is only called once.

For example if I configure both wit and luis and they both match the one which is most confident is used.

Applying this to regex was tricky as it doesn't provide a confidence, so I had to decide on a way to calculate this myself. Here were my thoughts when implementing #311:

- Matches from APIs such as LUIS should usually win over regex, therefore regex should have a lower score distribution.
- The more complicated the regex the higher the score should be. Currently length is used to calculate this.
- Regex skills should have some kind of upper limit on their score.

Therefore I think the same principals should be applied here, but I'm keen to know what you think!

**Comment by anxodio** [comment]
> Matches from APIs such as LUIS should usually win over regex, therefore regex should have a lower score distribution.

I'm thinking about this and I'm not sure if I agree. The point for me is that NLU APIs are less specific than regex or parse.

For example, you add a _greetings_ intent to some NLU training with various sentences like 'hello', 'hello opsdroid', 'hi', 'hello there', 'whats up', 'good morning'...
And you have the min-score at 0.6.

Then you have a regex matcher with something like 'hello from (?P<location>\w+)!'.

If a user writes "hello from Barcelona!" opsdroid will prioritize the NLU response, because it's almost secure that the NLU platform will detect the intent into the sentence.

So you regex will be never executed, even being more specific.

**Comment by jacobtomlinson** [comment]
Yep that's totally fair! Thanks for the feedback. 

Do you have any thoughts on an alternative approach?

**Comment by anxodio** [comment]
I think I would prioritize regex and parse over NLU engines, because they are more specific.
My point here is that if one developer is using an NLU engine, probably most of his/her opsdroid skills will be under the NLU engine. So if it's using some regex/parse, will be for something more concrete and if the regex/parse skill matches, probably it's the expected result of the developer.

My bet will be prioritize always parse > regex > NLU, from more specific to less specific, and remove score from parse/regex, or just use it if two different regex/parse are matching at the same time.

But, this is my experience and opinion. I don't know any real use cases other than mine, so I think the best strategy here is talk with the community and users, and try to discover what would be the preferred way to resolve this kind of decision.

**Comment by anxodio** [comment]
I will let this PR in standby waiting for #458 , because the final implementation will change depending on the resolution of the issue.

**Comment by jacobtomlinson** [comment]
#458 has gone stale now so I'm going to close this off. Would be great to revisit it though.

**Pull request closed without merging**
