### PR TITLE
Add a SIGHUP handler to reload opsdroid

### LINKED ISSUE #1631: Add a SIGHUP handler to reload opsdroid
Many linux daemons respond to the [`SIGHUP`](https://en.wikipedia.org/wiki/Signal_(IPC)#SIGHUP) signal by reloading their configurations. Combined with opsdroid's `no_cache: true` this could be used to reload a skill (or other plugin) while developing it.

This should be added in the same manner as the [existing handlers](https://github.com/opsdroid/opsdroid/blob/master/opsdroid/core.py#L56-L60).

### PR DESCRIPTION
**Pull request by MrNaif2018**
# Description

This PR adds ability to reload opsdroid by SIGHUP signal.

Should I also add this to documentation somewhere? In overview page?
Also: from what I see sigint and other signals are not tested, should I add tests for sighup?
Also, glad to see that opsdroid is improving! Lots of changes since my last contributions during previous Hacktoberfest :tada: 

Fixes #1631

## Status
**READY** 

## Type of change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

`opsdroid start` in one terminal, in other one `kill -SIGHUP <pid>`
Opsdroid successfully restarted and used new configuration file.
изображение

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Cadair** [comment]
More tests are never a bad thing!

Thanks for the PR!

**Comment by MrNaif2018** [comment]
Hmm, tox seems to catch sighup signal and make it an error. Is it possible to make it not do that?

**Comment by FabioRosado** [comment]
Hello @MrNaif2018 thank you for raising this PR and happy Hacktoberfest! Glad to see you back, I'm not sure if we can make tox not pick up that signal, perhaps if we mock it or the method it would stop that from happening?

**Comment by MrNaif2018** [comment]
I have fixed the signal test by wrapping all the code in a thread so sending signals to that thread and not main one.
Windows tests fail because SIGHUP is unsupported on windows. Should I add `pytest.skip` inside that test?
Like so:
```
if os.name == "nt":
    pytest.skip("SIGHUP unsupported on windows")
```

**Comment by FabioRosado** [comment]
I think that could be a good way to deal with the failures if SIGHUP isn't supported 👍

**Comment by MrNaif2018** [comment]
Now the signals test is skipped on windows, so test suite passes

**Review by FabioRosado — APPROVED** [review]
Thank you so much for updating the PR 👍

**Pull request merged**
