### PR TITLE
Add handling of LeaveRoom event for matrix.

### PR DESCRIPTION
**Pull request by xloem**
# Description

Adds handling of the LeaveRoom event to matrix, so that matrix rooms may be left.

This was simply missing functionality for a test locally.

## Status
**READY**

## Type of change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- `opsdroid.send(LeaveRoom(target = '#test-bot:matrix.org', connector = opsdroid.get_connector('matrix')))`
- Added a test for the call.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by FabioRosado — CHANGES_REQUESTED** [review]
Hello @xloem  thank you for opening this PR and working on this! 

Could I ask you to create a test for this event so coverage gets back to normal and we can merge the PR? 😄

**Review by FabioRosado — APPROVED** [review]
Brilliant thank you for adding the test!

**Comment by Cadair** [comment]
A good thing to do would be to add the ability for the matrix connector to emit these events as well, i.e. to allow people to respond to someone leaving. If you don't want to do that in this PR then we should open an issue for it.

**Review by jacobtomlinson — APPROVED** [review]
This has sat for a long time and looks good to merge so I'm going to do it.

**Pull request merged**
