### PR TITLE
Make all tests offline #593 

### PR DESCRIPTION
**Pull request by athanikos**

### CODE REVIEW

**Comment by athanikos** [comment]
if this is ok then the "Make all tests offline #593 #1004 PR" should be closed.
This is formatted so that linx is passing  and reuses the requirements file in th root folder as a parameter  whereas the other one was not passing due formatting and it used a requirements file created within the   "tests/mockmodulers/connectors" folder.

**Comment by FabioRosado** [comment]
Hello thank you for this, did you meant to create another PR for this issue?
I'm just checking with you to decide if I should close the other PR or not since I will not be able to merge a PR that has failing tests 👍

**Comment by athanikos** [comment]
No I did not mean to do so.  I am a rookie on this tool, so I am not sure why this happened.
You can close the other one (as you did) and keep this one for review.

**Comment by athanikos** [comment]
Could anyone review this one and let me know if any issues?

**Comment by FabioRosado** [comment]
Hey @athanikos  apologies for not replying earlier I kind of forgot to review the PR i'm going to do that now 👍

**Comment by FabioRosado** [comment]
I've just checked these changes and they look good. From your tests was this the only test that was causing issues when offline? Or there are more tests that would fail because no connection is available?

**Comment by athanikos** [comment]
Sorry accidentally closed it and reopened the PR.

I modified three methods :
1.  tests/test_loader.py::TestLoader::test_install_default_remote_module
I mocked the git clone method which was calling the clone method to get the files from the internet. Then I added side_effect = copy requirements file   (simulates installation by just copying that file) 
2.  tests/test_loader.py::TestLoader::test_install_gist_module_file
3.  tests/test_loader.py::TestLoader::test_install_specific_local_path_module
Those two methods had git_clone methods twice in place . I replaced the first call in each method  with with os.makedirs (simulates the installation of git modules) Th second call to git clone was mocked.

Then I run all tests by disabling the wired connection and all three passed (previously failing when no internet connection )

**Comment by FabioRosado** [comment]
I've just realised that, apologies I miss-read the changes.
I'm happy with this and I'm going to merge them into the core! Thank you so much for working on this issue and helping us with it 👍 

We give stickers for new contributors if you would like to get some then please send your home address by DM to [opsdroid twitter account](https://twitter.com/opsdroid) 😄

**Pull request merged**
