### PR TITLE
Replace except pass with contextlib.supress

### PR DESCRIPTION
**Pull request by FabioRosado**
# Description

I subscribe to Dan Bader daily python tips, on one of those emails he showed how you can ignore specific exceptions in a better way than using `except <exception> : pass` I remembered that we have a few bits of code like this so I decided to try and refactor the code in order to use the suggested `with contextlib.suppress(<exception>):`

Everything seems to be working fine, but I'm not sure if this improves readability since new people might need to search what the heck does contextlib.supress means (I didn't know about it before). 

Let me know if this is good or not 👍 

Fixes #<issue>

## Status
**READY**

## Type of change

_Please delete options that are not relevant._

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
- Documentation (fix or adds documentation)

# How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration._

- Tox - all green
- Ran opsdroid all good

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by FabioRosado** [comment]
That’s a good question I assume that if we suppress Exception there python will still try to run the await skill() if an exception happens it will suppress it and run the following code which could be the next bit:
If message... logger...

I will need to give it a test tho. I’m currently on holidays but I’ll be back Friday night so I can give it a go Saturday 😀👍

**Comment by FabioRosado** [comment]
I played around with this idea. If we suppress Exception then when we do this bit:
```if message:
...
```
I get the exception `TypeError: 'NoneType' object is not subscriptable` if we take this conditional then we get an AttributeError because message is None and it doesn't have the `respond` method.

I could only test this with tox because I am unable to run opsdroid through pycharm due to click giving me an encoding error (I tried to export the LC_ALL and LANG env var but didn't help - same when I add them to pycharm settings).

So I'm not sure if we supress the Exception and do a type check if message is none then get those error messages?

**Comment by jacobtomlinson** [comment]
Ok no worries. Worth a try! Are you ready to merge the other changes?

**Comment by FabioRosado** [comment]
I was reading the contextlib documentation and didn't find any method that could help with the broad exception as well we might need to think about something else as for merging yeah I'm happy with it 😄

**Pull request merged**
