### PR TITLE
Fix opsdroid failing if Rasa NLU is not available

### PR DESCRIPTION
**Pull request by FabioRosado**
# Description

I've sent a message about this in gitter but with all the chatter I think it got lost. Anyhow, this seems to fix the issue #412 a simple try/except made opsdroid work without any problems. I'm not sure if this is the best option to fix this issue tho.

When running opsdroid with rasanlu set on the config file the debug console shows this:

```
DEBUG opsdroid.core: Parsing input: hi
DEBUG opsdroid.core: Processing parsers...
DEBUG opsdroid.core: Checking Rasa NLU...
ERROR opsdroid.parsers.rasanlu: Unable to connect to Rasa NLU
opsdroid> ERROR opsdroid.parsers.rasanlu: Rasa NLU error - No intent found. Did you forget to create one?
DEBUG root: Responding with: Hi fabiorosado
```

The reason why I decided not to create a logging function on the pass method was because of the previous logging  message when `clientOSError` is raised "Unable to connect to Rasa NLU"

It's also possible to make opsdroid work when using the except: `aiohttp.client_exceptions.ClientConnectionError` but since we are already raising ClientOSError in the parse function, I've decided to just just ClientOSError (as both except makes opsdroid work)

Would love to know your opinion on this. It will probably need a test on the try/except which I can create if needed.

**Fixes** #412

## Status
**READY** | ~~**UNDER DEVELOPMENT**~~ | ~~**ON HOLD**~~

## Type of change

_Please delete options that are not relevant._

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration._

- Tox - all green
- Ran opsdroid - all good

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Thanks for looking at this. I'm happy with your solution.

If you could add a test that would be great.

**Comment by FabioRosado** [comment]
So I kind off used the example of `test_get_existing_movels` to test if the raise would be called.  The test passes but the coverage is still down, the issue might be because I'm testing if ClientOSError is raised but giving the status of `ConnectionRefusedError` as this is what we get when Rasa NLU is not available.

 Is there any better way to test an except:pass? If there is none I'll try to check with ClientOSError to see if it helps with the coverage.

Also, what's your opinion about adding a comment above the pass statement explaining why no logging message was created?

**Comment by jacobtomlinson** [comment]
You need to get it to raise within the try using a side effect. Then you'll see if it calls the pass properly.

**Comment by FabioRosado** [comment]
Okay that was actually easier than I expected haha I thought setting the result as ClientOSError would work but I was mistaken. Thank you for the help Jacob 👍

**Pull request merged**
