### PR TITLE
Allow skip training rasa model on startup

### LINKED ISSUE #1853: Use pre-trained Rasa model.
# Description
There is no option to take a pre-trained Rasa model (perhaps trained on a more powerful machine) and use that for predictions instead of training a new model each time opsdroid is started.

## Expected Functionality
There should be a configuration option under something such as `parsers->rasanlu->no-train` which by default is false, but can be set to true in order to prevent opsdroid sending the request to re-train each time.

## Experienced Functionality
No such option exists.

## Versions
- **Opsdroid version:**0.23.0
- **Python version:**3.9.2
- **OS/Docker version:**Debian 11

### PR DESCRIPTION
**Pull request by FabioRosado**
# Description

Fixes #1853

This issue seemed like an easy win so I added a flag to allow setting the training on/off for the Rasa NLU parser. 

## Status
**READY** | ~~**UNDER DEVELOPMENT**~~ | ~~**ON HOLD**~~

## Type of change

- New feature (non-breaking change which adds functionality)
- Documentation (fix or adds documentation)

# How Has This Been Tested?

- Added breakpoint to confirm that we skip the training on startup
- Tox all green

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Cadair** [comment]
Seems fine @oleg-fiksel rewrote the rasa parser iirc, so wonder if they have any comments.

**Review by jacobtomlinson — APPROVED** [review]
This looks great thanks!

**Comment by oleg-fiksel** [comment]
I think we should make the check (load or not to load the model) not in core.py but in rasanlu.py (func `train_rasanlu`).
Because if we completely ignore `train_rasanlu` we ignore the `_check_rasanlu_compatibility` and therefore will get an error if the Rasa API isn't compatible with our implementation.

We should probably move the call of `_check_rasanlu_compatibility` some place before ether way because if no intens are found (https://github.com/FabioRosado/opsdroid/blob/fr/rasa/opsdroid/parsers/rasanlu.py#L157) the compatibility check is also not called.

**Comment by jacobtomlinson** [comment]
Sounds good @oleg-fiksel. Do you feel like raising a follow up PR to this one?

**Comment by oleg-fiksel** [comment]
Yes. I plan to work on Rasa Matcher on Christmas holidays. Can this wait until then?

**Comment by jacobtomlinson** [comment]
Sure

**Comment by bparbhu** [comment]
So in this fix was this done with the use of a container that was spun up or a rasa server which already trained a model and the config options just point you to the file path and model name? The reason I'm asking is I'm trying to do the same in Docker-compose and I am spinning up my rasa instance at the same time. So would this have worked in a situation where there was already a rasa instance with a trained model?

**Comment by oleg-fiksel** [comment]
> I think we should make the check (load or not to load the model) not in core.py but in rasanlu.py (func `train_rasanlu`). Because if we completely ignore `train_rasanlu` we ignore the `_check_rasanlu_compatibility` and therefore will get an error if the Rasa API isn't compatible with our implementation.
> 
> We should probably move the call of `_check_rasanlu_compatibility` some place before ether way because if no intens are found (https://github.com/FabioRosado/opsdroid/blob/fr/rasa/opsdroid/parsers/rasanlu.py#L157) the compatibility check is also not called.

Here's the promised PR: #1886 🙂 
Sorry for quite a big delay.

**Pull request merged**
