### PR TITLE
Error handle in matrix connector

### LINKED ISSUE #1792: Matrix connector AttributeError 'RoomContextError' object has no attribute 'event'
# Description
Randomly the matrix connector will crash when connected to a public room.

## Steps to Reproduce
Create a skill and point it to `#geeklab:linuxdelta.com` and wait for people to start talking.

## Expected Functionality
For the connector to handle when this attribute doesn't exist.

## Experienced Functionality
```
Traceback (most recent call last):
  File "/home/sleuth/.local/bin/opsdroid", line 33, in <module>
    sys.exit(load_entry_point('opsdroid==0.22.0', 'console_scripts', 'opsdroid')())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/opsdroid/cli/start.py", line 43, in start
    opsdroid.run()
  File "/usr/lib/python3.9/site-packages/opsdroid/core.py", line 172, in run
    self.eventloop.run_until_complete(self.start())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/opsdroid/core.py", line 195, in start
    await self._run_tasks()
  File "/usr/lib/python3.9/site-packages/opsdroid/core.py", line 206, in _run_tasks
    await asyncio.gather(*self.tasks)
  File "/usr/lib/python3.9/site-packages/opsdroid/connector/matrix/connector.py", line 345, in listen
    async for event in self._parse_sync_response(response):
  File "/usr/lib/python3.9/site-packages/opsdroid/connector/matrix/connector.py", line 323, in _parse_sync_response
    yield await self._event_creator.create_event(
  File "/usr/lib/python3.9/site-packages/opsdroid/events.py", line 34, in create_event
    return await self.event_types[event[self.dispatch_key]](event, target)
  File "/usr/lib/python3.9/site-packages/opsdroid/connector/matrix/create_events.py", line 89, in create_room_message
    return await self.message_events[msgtype](event, roomid)
  File "/usr/lib/python3.9/site-packages/opsdroid/connector/matrix/create_events.py", line 107, in create_message
    kwargs["linked_event"] = await self.create_event_from_eventid(
  File "/usr/lib/python3.9/site-packages/opsdroid/connector/matrix/create_events.py", line 34, in create_event_from_eventid
    event_json = room_context.event.source
AttributeError: 'RoomContextError' object has no attribute 'event'
```

## Versions
- **Opsdroid version:0.22.0**
- **Python version: 3.9.5**
- **OS/Docker version: Manjaro and Docker 20.10.7**

## Configuration File
My full skill and a default config can be found at https://gitlab.com/Sleuth56/Matrix-Aggregator

```yaml
welcome-message: false

## Connector modules
connectors:
#  ## Matrix (core)
  matrix:
    # Required
    mxid: "@questions:server.com"
    password: "*************"
    # A dictionary of multiple rooms
    # One of these should be named 'main'
    rooms:
      'main': '#BotTesting:server.com'
    # Optional
    homeserver: "https://server.com"
    nick: "Questions"  # The nick will be set on startup
    room_specific_nicks: False  # Look up room specific nicknames of senders (expensive in large rooms)
    enable_encryption: True
    device_name: "opsdroid"
    device_id: "*******" # A unique string to use as an ID for a persistent opsdroid device
    # store_path: "/root/.config/opsdroid/Matrix_cache/" # Path to the directory where the matrix store will be saved
    store_path: "Matrix_cache"

databases:
  sqlite:
    # path: "/root/.config/opsdroid/messages.db"
    path: "messages.db"

skills:
  matrix-aggregator:
    module: 'aggregatorSkill'
    # path: /root/.config/opsdroid/Skill/
    # path: Skill
    logging: True
    destination_rooms: ["!room:server.com", "!room:server.com"]
    delete_message: "I deleted your entire message."
    sent_ack: "I sent your message!"
    nothing_to_send: "I don't have anything to send"
    nothing_to_preview: "Their isn't anything to preview"
    header: "<h2>{user_name} said </h2>"
```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.

### PR DESCRIPTION
**Pull request by DiptoChakrabarty**
# Description
https://github.com/opsdroid/opsdroid/blob/7615eaa4aa45fb05037911f94d5585856d10cb31/opsdroid/connector/matrix/create_events.py#L33-L35

Instance type of returned room context is compared , if incorrect response is returned a log of error is shown and eventid is returned else the event is created and returned 

Fixes #1792 

## Status
READY

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

pip pre commit has been installed and all tests by tox have been run as per instructions

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Cadair** [comment]
Thanks a lot for the PR, the fix looks like the right one.

I think this should have a regression test to make sure we don't accedentially reintroduce this bug in the future. Adding a test for this would involve adding one to the "new style" test file: https://github.com/opsdroid/opsdroid/blob/master/opsdroid/connector/matrix/tests/test_event_parsing.py

You would want to directly test the behaviour of the `MatrixEventCreator.create_event_from_eventid` method, so there shouldn't be too much setup you need to do. You will want to use the `@pytest.mark.add_response` decorator e.g.:

https://github.com/opsdroid/opsdroid/blob/d8e985c9983a7b24a862ecb15a882147e2105e0d/opsdroid/connector/matrix/tests/test_event_parsing.py#L20-L24

to mock responses to the event context API https://spec.matrix.org/unstable/client-server-api/#event-context you would want to test both the response where the event was found and the error response where the matrix event wasn't found.

**Comment by Cadair** [comment]
The test didn't pass because you are missing a roomid parameter: https://github.com/opsdroid/opsdroid/pull/1837/checks?check_run_id=3825752319#step:8:1949

you can run the tests locally using [tox](https://tox.wiki/en/latest/):
```
pip install tox
tox -e py39
```
(replace py39 with whatever version of python you are using)

so that you don't have to wait for me to approve the CI before you see the errors.

**Comment by DiptoChakrabarty** [comment]
Hey I have formatted the json response and updated the test but I always get this error 
Selection_176

and this during assertinstance
Selection_177

**Comment by DiptoChakrabarty** [comment]
the incorrect eventid test is passing but the correct eventid test is not passing I am checking on it

**Comment by Cadair** [comment]
> that means it is unable to create the room in the first place and throwing an error

Where is this happening? I thought we should only be testing a small part of the code here, so this wouldn't be happening?

(sorry for being quiet last week, was having a very busy week!)

**Comment by DiptoChakrabarty** [comment]
> Whe



> Where is this happening? I thought we should only be testing a small part of the code here, so this wouldn't be happening?

I am not sure, in the code 
```sh
room_context = await self.connector.connection.room_context(roomid, eventid, 1)
        if not isinstance(room_context, nio.responses.RoomContextResponse):
            _LOGGER.error(f"Unable to fetch room context with event id {eventid}")
            return eventid
```
it is going to the logger part and returning the eventid (for the test where the room creation should happen) , hence the test is failing as no json is returned but a string is returned , so I was wondering if the roomid was causing this issue

**Pull request closed without merging**
