### PR TITLE
Add LUIS parser/matcher

### PR DESCRIPTION
**Pull request by pohzipohzi**
fix for #252 

Some notes: 

I used the sample Calendar pre-built entity provided by microsoft, and tested for the action `Calendar.Add`. `LUIS` doesn't offer the same `speech` return as `api.ai` does (at least I don't think I can find it), so I tried to parse the message returned in a similar way as `api.ai`

example `__init__.py`
```
from opsdroid.matchers import match_luisai_intent

@match_luisai_intent('Calendar.Add')
async def passthrough(opsdroid, config, message):
    if message.luisai["topScoringIntent"]["score"]:
        await message.respond(str(message.luisai["topScoringIntent"]["score"]))

```

example configuration.yaml
```
##                      _           _     _
##   ___  _ __  ___  __| |_ __ ___ (_) __| |
##  / _ \| '_ \/ __|/ _` | '__/ _ \| |/ _` |
## | (_) | |_) \__ \ (_| | | | (_) | | (_| |
##  \___/| .__/|___/\__,_|_|  \___/|_|\__,_|
##       |_|
##                   __ _
##   ___ ___  _ __  / _(_) __ _
##  / __/ _ \| '_ \| |_| |/ _` |
## | (_| (_) | | | |  _| | (_| |
##  \___\___/|_| |_|_| |_|\__, |
##                        |___/
##
## A default config file to use with opsdroid

## Set the logging level
# logging:
#   level: info
#   path: opsdroid.log
#   console: true

## Set the location for opsdroid to install modules
# module-path: "."

## Show welcome message
welcome-message: true

## Configure the web server
# web:
#   host: '127.0.0.1'
#   port: 8080
#   ssl:
#     cert: /path/to/cert.pem
#     key: /path/to/key.pem

## Parsers
parsers:
#   - name: regex
#     enabled: true
#
#   - name: crontab
#     enabled: true
#
   - name: apiai
     access-token: "<access-token>"
     min-score: 0.6

   - name: luisai
     appid: "<application-id>"
     appkey: "<subscription-key>"
     verbose: True
     min-score: 0.6


## Connector modules
connectors:
  - name: shell
  - name: websocket

  # Uncomment the connector(s) that you wish opsdroid to work on
#  ## Slack (https://github.com/opsdroid/connector-slack)
#  - name: slack
#    # Required
#    api-token: "zyxw-abdcefghi-12345"
#    # optional
#    bot-name: "mybot"       # default "opsdroid"
#    default-room: "#random" # default "#general"
#    icon-imoji: ":smile:"   # default ":robot_face:"
#
#  ## Facebook (https://github.com/opsdroid/connector-facebook)
#  - name: facebook
#    # Required
#    verify-token: aabbccddee
#    page-access-token: aabbccddee112233445566
#    # Optional
#    bot-name: "mybot" # default "opsdroid"
#
#  ## Twitter (https://github.com/opsdroid/connector-twitter)
#  - name: twitter
#    # Required
#    consumer_key: "zyxw-abdcefghi-12345"
#    consumer_secret: "zyxw-abdcefghi-12345-zyxw-abdcefghi-12345"
#    oauth_token: ""zyxw-abdcefghi-12345-zyxw-abdcefghi-12345"
#    oauth_token_secret: "zyxw-abdcefghi-12345-zyxw-abdcefghi-12345"
#    # Optional
#    enable_dms: true    # Should the bot respond to Direct Messages
#    enable_tweets: true # Should the bot respond to tweets
#
#  ## Telegram (https://github.com/opsdroid/connector-telegram)
#  - name: telegram
#    # Required
#    token: "123456789:ABCDEFGHIJKLMNOPQRSTUVWXYZ-ZYXWVUT"  # Telegram bot token
#    # Optional
#    update_interval: 0.5  # Interval between checking for messages
#    default_user: user1   # Default user to send messages to (overrides default room in connector)
#    whitelisted_users:    # List of users who can speak to the bot, if not set anyone can speak
#      - user1
#      - user2

## Database modules (optional)
# databases:
#   - name: mongo
#     host:       "my host"     # (Optional) default "localhost"
#     port:       "12345"       # (Optional) default "27017"
#     database:   "mydatabase"  # (Optional) default "opsdroid"

## Skill modules
skills:

  ## Hello world (https://github.com/opsdroid/skill-hello)
  # - name: hello

  ## Last seen (https://github.com/opsdroid/skill-seen)
  # - name: seen

  ## Dance (https://github.com/opsdroid/skill-dance)
  # - name: dance

  ## Loud noises (https://github.com/opsdroid/skill-loudnoises)
  # - name: loudnoises

   # Configurations for other skills uncomment desired skill to activate it.
#
#  ## Grafana (https://github.com/opsdroid/skill-grafana)
#  - name: grafana
#    room: "#monitoring"  # (Optional) room to send alert to
#
#  ## Travis (https://github.com/opsdroid/skill-travis)
#  - name: travis
#    room: "#monitoring"     # (Optional) room to send alert to
#    travis_endpoint: "org"  # (Optional) endpoint for travis, change to "com" if using enterprise Travis CI
#
#  ## Devtools (https://github.com/opsdroid/skill-devtools)
#  - name: devtools
#
#  ## Food (https://github.com/opsdroid/skill-food)
#  - name: food
#    api-key: "myapikeyfromfood2fork"  # Required
#
#  ## Magpi (https://github.com/opsdroid/skill-magpi)
#  - name: magpi
#    room: "#raspberrypi"    # (Optional) room to send notifications to
#
#  ## Google it (https://github.com/opsdroid/skill-google-it/)
#  - name: google-it
#    # Use Google search engine (Default)
#    engine-url: https://www.google.co.uk/
#    query-arg: search?q=
#    # Other search engines that can be used (keep only one active at a time)
#    # Use Bing search engine
#    engine-url: https://www.bing.com/
#    query-arg: search?=
#    # Use DuckDuckGo search engine
#    engine-url: https://duckduckgo.com/
#    query-arg: ?q=
#    # Use Yahoo search engine
#    engine-url: http://search.yahoo.com/
#    query-arg: search?p=
#    # Use Aol search engine
#    engine-url: https://search.aol.co.uk/aol/
#    query-arg: search?query=
#    # Use Ask search engine
#    engine-url: https://uk.ask.com/
#    query-arg: web?q=
#    # Use Wolframalpha search engine
#    engine-url: https://www.wolframalpha.com/input/
#    query-arg: ?i=
#
#  ## API.AI (https://github.com/opsdroid/skill-apiai)
  - name: apiai
    include:
      - smalltalk
    exclude:
      - smalltalk.agent

  - name: luisai
    include:
      - Calendar.Add
#
#  ## Vault (https://github.com/opsdroid/skill-vault)
#  - name: vault
#    # Required
#    vault-url: https://vault.example.com:8443
#    vault-token: aabbccddee1122334455
#    # Optional
#    announce-on-seal: false   # Announce the vault status in the default room on seal
#    announce-sealed: true     # Announce the vault is sealed hourly
#    announce-unsealed: false  # Announce the vault is unsealed hourly
#
#  ## ISS (https://github.com/opsdroid/skill-iss)
#  - name: iss
#    # Required
#    api-key: "mygooglemapsapikey"
#    # Optional
#    zoom: "5"
#    map-size: "1024x768"
#    map-type: "hybrid"    # hybrid, satellite or roadmap
#
# ## HomeAssistant (https://github.com/opsdroid/skill-homeassistant)
#  - name: homeassistant
#    room: "#homeassistant"

```

example command: `schedule meeting`

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Many thanks for this! This looks like a really interesting PR.

It looks like it needs some unit tests and it needs some work to get it to lint, but apart from that it should be excellent. Could you please correct this?

I'm afraid I'm going away for a week so I wont be able to review your changes until next weekend, sorry!

**Comment by pohzipohzi** [comment]
Hey @jacobtomlinson I tried to do as you said. There is a small decrease in coverage as I'm not sure how to test for the `aiohttp.ClientOSError` (similar to the test for apiai). Hopefully its alright!

**Comment by jacobtomlinson** [comment]
Thanks for this! Sorry I haven't reviewed it yet I've been on holiday.

I'm happy with a tiny decrease in coverage for now, I'd rather get this code in than force you to bash your head against the table trying to solve this! 

I'm just going to give it a local test myself but once I've done that I'll merge it 😄.

**Comment by jacobtomlinson** [comment]
Awesome I've tested it locally and it works fine for me.

The last thing I need you to do before I can merge it is add a documentation page for the matcher similar to the [existing ones](https://github.com/opsdroid/opsdroid/tree/master/docs/matchers) and also reference it in the [mkdocs file](https://github.com/opsdroid/opsdroid/blob/master/mkdocs.yml).

**Comment by pohzipohzi** [comment]
@jacobtomlinson here you go :)

**Comment by jacobtomlinson** [comment]
Awesome work!

**Comment by jacobtomlinson** [comment]
Ping me your address via DM on [Twitter](https://twitter.com/_jacobtomlinson) or [Gitter](https://gitter.im/opsdroid) and I'll post you some [opsdroid stickers](https://medium.com/opsdroid/stickers-for-contributors-a0a1f9c30ec1)!

**Pull request merged**
