### PR TITLE
Add issue/PR template - issue #284

### PR DESCRIPTION
**Pull request by FabioRosado**
Decided to give this a try I used bits of other templates I found online to create these, let me know if you are okay with them or you'd rather have something else on them.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Wow! I did not expect that so fast, good work!

I really like what you've done, the only change I would suggest is removing the example config as it's rather large and folks will just be deleting it and adding their own anyway. You could just replace it with a code block which says `your config goes here`.

**Comment by jacobtomlinson** [comment]
Looks like something has gone wrong with your push here. The diff has now changed to show the #275 commits.

**Comment by FabioRosado** [comment]
Sorry it took me a while to fix the issue because I messed up a pull/rebase and lost all the work had to reflog the changes.

Today I've been doing a lot of waiting around because i'm on call for work so I've seen the issues and thought this one I could come up with something quickly haha

**Comment by jacobtomlinson** [comment]
Awesome stuff!

**Pull request merged**
