### PR TITLE
import slack only one time to improve code quality

### LINKED ISSUE #1377: Slack is imported more than one time
# Description
Please include a summary of the issue.
Slack is imported more than one time in tests/test_connector_slack.py

## Steps to Reproduce
Please also include relevant information and steps to reproduce the bug/issue.
N/A

## Expected Functionality
Explain what should happen.
Import should happen only one time

## Experienced Functionality
Explain what happened instead(Please include the debug log).

## Versions
- **Opsdroid version:**
- **Python version:**
- **OS/Docker version:**

## Configuration File
Please include your version of the configuration file below.

```yaml
# Your code goes here.

```

## Additional Details
Any other details you wish to include such as screenshots, console messages, etc.
screenshots:-

Screenshot (10)_LI
Screenshot (11)_LI

I would like to work on this issue

### PR DESCRIPTION
**Pull request by himanshu010**
# Description

Fixes #1377 

## Status
**READY** 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- Test A
- Test B

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by himanshu010** [comment]
@FabioRosado does this usually take this much time or is it only happening in this case ?
Because I think CI does not take more than 10mins

**Comment by himanshu010** [comment]
@FabioRosado can I get some stickers now? 😅😅

**Comment by jacobtomlinson** [comment]
I would not consider this a meaningful change and it does not address an open issue. If you want some stickers please check out the open issues and raise a more impactful PR.

**Comment by himanshu010** [comment]
> I would not consider this a meaningful change and it does not address an open issue. If you want some stickers please check out the open issues and raise a more impactful PR.

ok I will try to solve some of the open issues btw I am here only for the stickers😅 and I will try my best to gain some😁

**Pull request merged**
