### PR TITLE
Adding try/except to welcome_message

### PR DESCRIPTION
**Pull request by accessdenied12**
This will keep the key error from breaking the start process.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Nice work thanks for this! Could you please add a test which follows the except block and asserts that it doesn't raise.

**Comment by accessdenied12** [comment]
@jacobtomlinson - Thanks.  I've updated the unit test so that it checks to make sure nothing is sent back from the function if welcome-message is not present.  Let me know if you want me to change anything.

**Comment by jacobtomlinson** [comment]
This is perfect. It looks like the linter is failing you because line 103 is longer than 80 characters. Can you either break it over two lines or add a pylint disable comment so it's ignored.

**Comment by accessdenied12** [comment]
@jacobtomlinson - Sure thing.  Looks like the build is passing now in Travis 👍

**Comment by jacobtomlinson** [comment]
Awesome! Ping me your address via DM on twitter or Gitter and I'll post you some opsdroid stickers!

**Pull request merged**
