### PR TITLE
Add Polish translation

### PR DESCRIPTION
**Pull request by ziebam**
# Description

Added a Polish translation. Tried to stay as consistent as possible, but if we ever have other Polish contributors I'd be glad to have them double-check my work.

One issue I've noticed is inconsistency in logging messages. Sometimes the names are capitalized, sometimes they aren't; sometimes there is a dot at the end of a sentence and sometimes there isn't. I think it raises another issue of unifying these messages so they follow more-or-less the same convention. I could work on that if you want me to.

~~Excuse the goofy name of the branch. Localization is used interchangeably with translation in Poland and I didn't know they were different things. :D~~

## Status
**READY**

## Type of change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- Compiled with `python setup.py compile_catalog` to make sure everything is matching.
- Tested preventively with `tox` – no failed tests.

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have made corresponding changes to the documentation (if applicable)
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by FabioRosado** [comment]
Thanks for working on this, it was quick haha 
I’ll ask my wife to double check the polish terms but will take me three days due to my weird work schedule.

You raised good points, feel free to raise an issue with them. You can also work on it if you have the time otherwise I’m sure someone else will take it on since that is a great issue for first time contributors 😄

**Comment by ziebam** [comment]
The main issue was with programming-related words like "parser" or "connector" since they theoretically have a Polish translation, but nobody uses it and they just call them by their English counterpart. I'm in no rush, so absolutely take your time!

**Comment by FabioRosado** [comment]
Yeah I see your point I don’t remember how I translated things to portuguese but we tend to use a lot of English terms as well. 

Im sure it will be okay to use English words since most things will be in polish anyway 😄👍

**Comment by ziebam** [comment]
Hey, thanks for the offer, but I'll pass on the stickers for now! It's nothing personal, I'm just very concerned about privacy in the internet. I'm simply happy to help. :D

**Pull request merged**
