### PR TITLE
adding Lex matcher/parser

### PR DESCRIPTION
**Pull request by slapula**
I am submitting this PR to satisfy #251.  This is still a bit of a work in progress at the moment while I continue testing.  I will update this PR when it is ready for final review.  Comments or feedback are welcome though at any point.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
This is awesome work!

Just had a look through the code and nothing glaring jumps out at me.

The tests are failing because pylint and flake8 aren't happy with the formatting. Have a look at the [errors](https://travis-ci.org/opsdroid/opsdroid/jobs/288071913) for more info. If you could correct these that would be great.

The other tests are failing because you haven't included `aiobotocore` in the requirements or setup file so it's failing to import in Travis.

**Comment by jacobtomlinson** [comment]
Sadly this does look like a duplicate of #263. You might want to liaise with @pohzipohzi  to see if the two approaches can be combined.

**Comment by jacobtomlinson** [comment]
Ignore my last message. I misread Lex as LUIS!

**Comment by slapula** [comment]
Yup, I'm working on cleaning this up and adding appropriate tests (although I'm not quite sure how to mock aiobotocore at the moment).

**Comment by jacobtomlinson** [comment]
Ok great! 

Looking at `aiobotocore` itself they seem to be using `moto` to mock the api endpoints themselves. You could look into doing that instead of mocking the library itself. See [their tests](https://github.com/aio-libs/aiobotocore/tree/master/tests) for inspiration. Just a thought, not necessarily the right answer.

One thing I've really found with creating this project is that testing an asyncio project is way harder than expected. Hopefully this area will mature with time.

**Comment by jacobtomlinson** [comment]
Also could you add a documentation page for the matcher similar to the [existing ones](https://github.com/opsdroid/opsdroid/tree/master/docs/matchers) and also reference it in the [mkdocs file](https://github.com/opsdroid/opsdroid/blob/master/mkdocs.yml).

**Comment by jacobtomlinson** [comment]
Hey @slapula. Thanks again for spending time on this. Any chance you can git this finished as I'm eager to merge it?

**Comment by slapula** [comment]
Yup, this is still on my radar.  The past week has been pretty busy for me.  I'm going to see if I can finish this up over the weekend.

**Comment by jacobtomlinson** [comment]
Awesome thanks. Let me know if you need a hand or if you don't have time.

**Comment by slapula** [comment]
I reviewed the aiobotocore tests and it seems like they are using existing functionality in Moto. Lex support doesn't exist there either so I'm not sure I can use it to test.  If you don't mind keeping this PR open a little while longer, I'd like to take a stab at adding support myself (It is Hacktoberfest after all).  If not, I could get this cleaned up and documented, merge it without the tests, and submit the Moto based tests PR later when Lex support is added.

**Comment by jacobtomlinson** [comment]
Let's leave this open for now. Keep me up to date with how you get on
adding lex support.

**Comment by jacobtomlinson** [comment]
@slapula did you manage to make any progress with this? I'm still very keen to get this feature in.

**Comment by jacobtomlinson** [comment]
Closing due to inactivity.

**Pull request closed without merging**
