### PR TITLE
Add asyncio docs and extend YouTube video text

### PR DESCRIPTION
**Pull request by TarunRKaushik**
# Description

Added references to asynchronous functions, changed description of video series and added a link to the video series in the "create your own skill" section. Basically worked on issue #437

**Fixes** #437

## Status
**READY**

## Type of change

- Documentation (fix or adds documentation)

# Checklist:

- [ ] I have performed a self-review of my own code
- I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by TarunRKaushik** [comment]
will do

**Comment by jacobtomlinson** [comment]
That's great! Also can you mention the `await` keyword too as it's important when responding to messages.

**Comment by TarunRKaushik** [comment]
done. anything else?

**Comment by jacobtomlinson** [comment]
Nope this looks good, I'll merge it now.

**Comment by jacobtomlinson** [comment]
Ping me your address via DM on [Twitter](https://twitter.com/_jacobtomlinson) or [Gitter](https://gitter.im/opsdroid) and I'll post you some [opsdroid stickers](https://medium.com/opsdroid/stickers-for-contributors-a0a1f9c30ec1)!

**Pull request merged**
