### PR TITLE
added better quick link for documentation resource

### PR DESCRIPTION
**Pull request by Swati4star**
# Description

A.dded better quick link for documentation resource
I had to go to each documentation folder to check the resource available inside. I have created a better index to directly go to required resource

## Status
**READY** 

## Type of change
- Documentation (fix or adds documentation)

# How Has This Been Tested?

Just the documentation chaneg

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by FabioRosado** [comment]
Hello @Swati4star  Thank you for raising this issue, you have mentioned something interesting.

@jacobtomlinson do you think we should replace the `docs/index.md` with a quick link menu like this instead of having the project `README.md` duplicated on index? 🤔

**Comment by Swati4star** [comment]
@FabioRosado Sure. but I'll suggest to remove index.md file.
The benefit of using "Readme.md" is, it is automatically rendered when link is opened
What I mean is, check this link https://github.com/Swati4star/opsdroid/tree/doc-fixes/docs. Readme is already shown at bottom.

**Comment by jacobtomlinson** [comment]
I'm not sure that this benefits the project. You have replaced a page filled with information for a list of links which are already available in the menu on the left hand side.

image

**Comment by jacobtomlinson** [comment]
Oh wait I see you haven intended this just for use within the GitHub repo! Sorry about that.

In that case I agree that we might want a `README.md` file within that directory to help people find things. But my preference would probably be to simply link people to the documentation website.

**Comment by Swati4star** [comment]
@jacobtomlinson  Are you suggesting some change in my PR here?

**Comment by Swati4star** [comment]
If you suggest, I can add both to the Readme.

**Comment by jacobtomlinson** [comment]
My concern is about keeping that list up to date.

**Comment by jacobtomlinson** [comment]
Could I get an opinion from another @opsdroid/maintainers bod? I'm worried this list is another thing to maintain and I'm not sure how much value it adds.

Looking at the insights/analytics over the last 14 days we've had 37 people hit this page and 99 hit the docs site. My preference would be to divert the GitHub traffic to readthedocs, rather than providing them links deeper into the GitHub docs.

**Comment by SolarDrew** [comment]
Hi @Swati4star, thanks for the PR. I'm inclined to agree with @jacobtomlinson, I think linking more directly to the docs is probably going to be more intuitive than asking people to look in the docs folder on GitHub. But I can also see the utility in having a list of quick links. 

Perhaps a reasonable middle-ground would be to add the links to the main project README? If we had a landing page for each of the headings (Connectors, Databases, etc.) then we could just link to those, which would reduce the maintainance burden and would mean the links wouldn't take up much space in the README, but it would make it easier for users to go straight to whichever part of the docs they need from the main GitHub page.

**Comment by Swati4star** [comment]
So, @SolarDrew You want to have all these links (and sublinks) in the main readme? or just the doc headings.

**Pull request closed without merging**
