### PR TITLE
Merge Slack and Websocket connectors to the core project

### PR DESCRIPTION
**Pull request by jacobtomlinson**
# Description

This PR is the start of the work on #185 by adding the Slack and Websocket connectors into the core project.

The loader now checks for connector modules within the opsdroid core library before looking to load an external plugin. This makes it fully backward compatible.

## Status
**UNDER DEVELOPMENT**

## Type of change

- Core maintenance

# How Has This Been Tested?

New unit tests have been added to fully test the code within the connectors, however the third party APIs have been mocked.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Thoroughly test both connectors.
- [x] Improve the connectors documentation to include tutorial like instructions on how to set it up.
- [x] Add documentation about the fact there are now builtin connectors.

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Still to do:
- [ ] Thoroughly test both connectors.
- [ ] Improve the connectors documentation to include tutorial like instructions on how to set it up.
- [ ] Add documentation about the fact there are now builtin connectors.

**Comment by FabioRosado** [comment]
I looked over at the code and I know you are still working on it. The idea is to move all the other connectors into opsdroid core right? Or slack will be the only one moved at the moment? (I guess people would use slack more than any of the others)

**Comment by jacobtomlinson** [comment]
Yeah the idea is to eventually move all the connectors and database modules into the core project. I just wanted to take it in small chunks as it is quite a lot of work. 

So this PR updated the loader to look for modules in the core project first and adds the first two connectors. Once it's finished and merged I'll start looking into the other modules. I was hoping for some of them like the [matrix connector](https://github.com/opsdroid/connector-matrix) which was writted by someone else that I could get them to help merge it in.

**Comment by FabioRosado** [comment]
I'm not sure if you are still working on this Jacob but I assume it's pretty much done, I got some time to go through it today and this looks good let me know if you want it merged now 😄 👍

**Comment by FabioRosado** [comment]
It’s okay it happens :D I’ve been busy learning js as well haha 
Do you need any help with documenting?

**Comment by jacobtomlinson** [comment]
If you're happy to help then yes please!

**Comment by FabioRosado** [comment]
Hey Jacob I just wanted to check with you a few things. For me to submit commits into your PR do I just need to add you as a remote on my end, create a branch and then push these changes into your own branch?

The tutorial do you want me to write just how to set it up (like config options and whatnot?)

The builtin connectors documentation should I just update the connector documentation and mention this fact, or would you prefer to have a new file for this?

Thanks

**Comment by jacobtomlinson** [comment]
Yes you should be able you add my fork as a remote.

I think we need to update the connector docs to say there are builtin connectors and you can use plugins. We should also have a documentation page for each built-in, like we have for parsers.

**Comment by FabioRosado** [comment]
I've changed just a bit of the documentation since you started with it anyway. I didn't create a tutorial on how to set it up because `slack.md` seems to be pretty self-explanatory, but if you would like to add an in-depth one I will be more than happy to create one. 

I have also tested to see if opsdroid would connect to slack and respond to `hello` and everything worked flawlessly 👍

**Comment by jacobtomlinson** [comment]
Sorry I haven't had a chance to look at this, been super busy this last week. Do you mean test failures of readthedocs failures?

**Comment by FabioRosado** [comment]
It's okay sometimes we get extremely busy with work and life 👍 
I was updating all the dependencies the other day and it seems that some tests either erroed (like the docker failed to connect to aws) or some python test (like pythong 3.5) failed because of timeout, not sure if the issue was within travis (it seems that week they had some issues) or if our tests don't help much haha

**Comment by jacobtomlinson** [comment]
Ah interesting! The tests seem to be passing here so perhaps you could raise it as a separate issue?

Thanks again for adding the documentation, huge help!

**Pull request merged**
