### PR TITLE
Test

### PR DESCRIPTION
**Pull request by sims34**
# Description

_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change._

Fixes #<issue>

## Status
**READY** | **UNDER DEVELOPMENT** | **ON HOLD**

## Type of change

_Please delete options that are not relevant._

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
- Documentation (fix or adds documentation)

# How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration._

- Test A
- Test B

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by FabioRosado** [comment]
This is some good work you started here. I guess you are still working on this so I'll leave my review for the future once you mark this as done.

A few things I've noticed though: 
- You changed a lot of files to just point at `+/home/simon/OpenSource/Python/opsdroid/` any reason why this happened? You will have to revert this changes in order to get the PR merged.
- You created this PR as a test, it's better to just create a real PR and just mention that this is a test to see how things go. The reason for this is that you can just work on your branch (test) and keep pushing commits to the branch and this PR will be updated. This will also make it easier for the maintainers when the time to merge comes.
- Again I know this was a test but is useful if you fill up the template that's provided when you start a new PR just to write your work so far and such. You can always edit and update it as you work on this PR.
- This last suggestion is just for your own mental sanity for the future - renaming branches to something meaningful will help a lot when you are working on different things in the same project so its good practice to just rename the branch (but then again if this was a test, the name is not too bad 😄 )

**Comment by sims34** [comment]
Hi @FabioRosado ,
Thk a lot for your advices, i'm going to work on it, but i so confused because my push command whould have puhed on my master branch  on my local repersitory the origin remote. I didn't get it how you received. Now thank to this i get some feedbacks, i promess it's not happen again :stuck_out_tongue_winking_eye:
Sims

**Comment by sims34** [comment]
This is what i did but i had some trouble for switch  from the test branch to the master branch of my local repo. Finally i did a '<git stash>' command and it's worked.   I'm going to try another PR with following your advices and see what it's look like what do you think ?

**Comment by FabioRosado** [comment]
The command git stash saves your changes away so you can do whatever you want. its useful when dealing with work in progress but you want to push something else.

**Comment by sims34** [comment]
I've just make my first PR right now, i've done again what i had started before the error message.
i've just set the comments for the 3 methods in the **helper.py**  file.
 you can check and send me some feedback
Thk for help
best reguards

**Pull request closed without merging**
