### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
This pull request adds backers and sponsors from your Open Collective https://opencollective.com/opsdroid ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Thanks for raising this! Really exciting to be part of Open Collective.

A few thoughts:
 - We already have an [issue template](https://github.com/opsdroid/opsdroid/blob/master/docs/ISSUE_TEMPLATE.md) could you please move the comment there instead of creating a new one.
 - We already have a [contributing documentation page](https://github.com/opsdroid/opsdroid/blob/master/docs/contributing.md). Could you please merge the credit section into that one.
- Please could you move the badges to the end of the list after gitter and not the beginning.

**Comment by jacobtomlinson** [comment]
Thanks for the updates. Could you just delete `.github/ISSUE_TEMPLATE.md` too as it is now not needed.

**Comment by jacobtomlinson** [comment]
Awesome thanks!

**Comment by jacobtomlinson** [comment]
I know this is a necessary Open Collective  requirement but you've still make a contribution to  opsdroid so ping address via DM on [Twitter](https://twitter.com/_jacobtomlinson) or [Gitter](https://gitter.im/opsdroid) and I'll post you some [opsdroid stickers](https://medium.com/opsdroid/stickers-for-contributors-a0a1f9c30ec1)!

**Comment by monkeywithacupcake** [comment]
No worries on the stickers - thanks! Neat project BTW.

**Pull request merged**
