### PR TITLE
raw_message kwarg addition to the Message class.

### PR DESCRIPTION
**Pull request by redfruitt**
# Description

The change allows to store complete message from a connector in its raw format, this allows for 
meta-data to be more readily available and prevents the need for extending the Message class with addition parameters

**Fixes** #443 

## Status
**READY** 

## Type of change

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Thanks for raising this!

You've had a couple of linter failures. You have a couple of lines which are too long, I would appreciate if you could fix that.

It is also complaining about too many attributes and too many args in the `Message` class. I'm happy that these limits are too low and I've raised #448 to resolve that. Once that's gone in I'll update this branch and those errors should go away.

**Comment by jacobtomlinson** [comment]
Ok that's cleared up the attribute and arg errors. So if you can just sort the long lines and documentation that would be great!

**Comment by jacobtomlinson** [comment]
Now you've introduced a bunch of training whitespace 😆.

**Comment by redfruitt** [comment]
Ok things should work now :D

**Comment by jacobtomlinson** [comment]
Nice!

**Comment by jacobtomlinson** [comment]
Ping me your address via DM on [Twitter](https://twitter.com/_jacobtomlinson) or [Gitter](https://gitter.im/opsdroid) and I'll post you some [opsdroid stickers](https://medium.com/opsdroid/stickers-for-contributors-a0a1f9c30ec1)!

**Pull request merged**
