### PR TITLE
Add documentation for maintainers

### PR DESCRIPTION
**Pull request by FabioRosado**
# Description

This is my first attempt at creating documentation for maintainers. I've used most of what you said @jacobtomlinson on #434 and just added some guide text.

Would love to hear your opinions about this and if I should add/remove or mention something else.

I also have a question about merging a PR. Should squash and marge be chosen when merging? What is the best way to do it? (So I can add it up in the documentation)

**Fixes** #434 (maybe?)

## Status
~~**READY**~~ | **UNDER DEVELOPMENT** | ~~**ON HOLD**~~

## Type of change

_Please delete options that are not relevant._

- Documentation (fix or adds documentation)

# Checklist:

- [ ] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Looks neat thanks! Some thoughts

### Code review

> You didn't write it yourself (this may not be practical yet, we should discuss it)

Let's discuss this now. 

Ideally the rule would be "All PRs must be reviewed by someone other than the author". I feel it is bad practice to raise a PR and then merge it youself without getting someone to review it. I know this is hypocritical as I do this all the time in opsdroid. I do it because there are not enough people in the community to review my work, however I would love to get to the point where my work is reviewed.

I don't want to burden you with reviewing all of my PRs. But maybe I'm wrong here, and perhaps you should review them.

What do you think? 

### Merge types

Yes I've been doing squash and merge. I feel this keeps the commit history neat as most additional commits are along the lines of "typo", "Fix broken test", "add test" etc. 

### It mentions me a lot

I want opsdroid to be a community project. For a long time I was the only member of the community, but I'm really excited that it's been growing 🎉. I feel this is a good time for me to transition from being the owner of the project to being the leader of the community.

There are lots of things that I am responsible for as the leader of the community, but I would love to delegate some of those things over time. So maybe we should start preparing for that now. 

For example instead of saying "If in doubt about a PR ping @jacobtomlinson" then it should say "If in doubt about a PR ping @opsdroid/maintainers". I appreciate that will still just be you pinging me for now, but when we add more maintainers in the future this will scale out better. 

Same goes for stickers. I paid for the first batch of stickers and they are physically at my house, so I need to be the one to send them out. But I want this to transition to the community buying the stickers and the maintainers sending them out, this may still end up being me putting the money in and doing the work but it 

The first step of this is setting up [Open Collective](https://opencollective.com/opsdroid) which means the financial aspect of it is now transparent and scalable, so in the future someone else could order the stickers and send them out and claim the money back from the community. 

So maybe people should DM @opsdroid on twitter instead of me directly. 

The counter argument to all of this is that open source projects often benefit from having a human face associated with it, this helps demonstrate that it isn't a faceless startup which is trying to get money but a passionate individual who wants to do something good for the community.

I would be interested in your thoughts on this too...

**Comment by FabioRosado** [comment]
**Code Review**
I agree with you that all PRs should be reviewed by someone before merging them, although in some cases I might not be the right person to review it simply because I lack experience in a lot of things. I can give my opinion but ever since I started contributing to opsdroid I go by - whatever you say its rule - because you did create opsdroid, you work on the field and you know way more than me haha
But I'd be happy to give my opinion on things.

**Merging**
I kind off guessed that you used squash but just wanted to be sure. I'll update the docs to mention this 👍 

**Mentioning you**
You raise good points, I didn't think long-term here.

I'm happy to change things around as you suggested. 

As for the stickers, I like the idea of the community ordering them and the maintainers sending them out in the future. Since you have access to the opsdroid twitter account it does make more sense pinging this account and it will leave your personal account a bit more free to do other things.

**Other stuff**
I'm thinking to move the `Maintainer scripts` bit from contributing.md to this document since this will be most relevant for maintainers, what do you think?

**Comment by anxodio** [comment]
About the code review and the sentence "All PRs must be reviewed by someone other than the author", I think we can get a balanced point if we define some rules. I am thinking about something like:
- If it's a critical bug solution and no one can review it fast, just merge it and review it later
- If it's a "normal" bug solution and in 2 days no one reviews it, just merge it
- If it's a new feature and in 5 days no one reviews it, just merge it
[...]

The number of days it's just an example, the point is the idea to try to get reviewed without burn people and without eternal PR

**Comment by FabioRosado** [comment]
Thats some good points about critical bug solution although if a maintainer has to accept the merge then he/she can just review the PR just to make sure it passes the tests and does solve the issue. So in a way, the PR will always be reviewed, maybe not in depth but a brief glance

**Comment by jacobtomlinson** [comment]
@anxodio yes I definitely agree with your points. 

@FabioRosado your opinions are really useful. Even if you're just asking why I've done something a certain way. It may cause me to rethink it. Also yes please move the maintainer scripts stuff.

**Comment by FabioRosado** [comment]
I thought  I had added the updated version before I left for my short holidays. I was wrong. 
So here's the updated version. What do you guys think about it? Anything else to change or its ready to merge? 😄

**Comment by jacobtomlinson** [comment]
I'm happy with it! Don't forget it add it to the index!

https://github.com/opsdroid/opsdroid/blob/master/mkdocs.yml

**Pull request merged**
