### PR TITLE
Update german translation

### PR DESCRIPTION
**Pull request by jos3p**
# Description

German translation updated.

## Status
**READY** 

## Type of change

- i10n

# How Has This Been Tested?

Spellchecker

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Awesome stuff thanks!

**Comment by jos3p** [comment]
Sorry to ask this but this PR merge seems to not count for hacktoberfests auto detection magic (still shows pending) (like for another contributor before?) i know last year it worked fine :(
image

**Comment by FabioRosado** [comment]
Isn't that because every PR you do has a 2 weeks waiting time before they check to see if it was accepted?

Digital Ocean added a 2 weeks gracing period for every PR due to spam, to get a PR accepted it needs to either be:

- merged
- Labelled as accepted
- Accepted by a maintainer 

So I'm assuming it's still on this grace period 🤔

**Comment by jos3p** [comment]
I'm not really sure as my two other already merged contributions are indeed on the 2 weeks maturetime, the third is still waiting to merge, but opsdroid is already merged and should show the countdown (again sorry to ask as its not really an opsdroid issue)

image

**Comment by FabioRosado** [comment]
I'm not entirely sure, unless they add some sort of timer before turning it? 

I've submitted some extra PRs to opsdroid and they aren't counted yet as well but all my 4 PRs where done in this repo and I got them counted so not sure 🤔

**Comment by jos3p** [comment]
I guess I was just to late then, i thought only the pullrequest time is important..
`The deadline for completions, merging, labeling, and approving is November 1.`
Sorry and thank you for your time

**Pull request merged**
