### PR TITLE
Update loader.py

### PR DESCRIPTION
**Pull request by Pranav-Jain**
# Description

Added full stops, where necessary to make the debugging statements consistent.

Fixes #<issue>
Fixes Issue #1137 

## Status
**READY**

## Type of change
- Documentation (fix or adds documentation)

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
@FabioRosado do we need to update the translations too when doing this?

**Comment by FabioRosado** [comment]
Since we are just doing small fixes like adding punctuation and use uppercase letters on the beginning of the sentences, the translations could stay the same unless someone wants to fix them.

These fixes won't change the translations much 🤔

**Comment by jacobtomlinson** [comment]
They wont but will the correct translations still be found because the string is changed within the `_(<string>)`?

**Comment by jacobtomlinson** [comment]
Yeah I think it has to be a perfect match.

**Comment by Pranav-Jain** [comment]
@FabioRosado By translations, do you mean the files at present at opsdroid/opsdroid/locale/ ?

**Comment by FabioRosado** [comment]
Yes you will have to update the translations. I might be wrong but I think if you run the command `python setup.py update_catalog`  all the translations should be updated with these logs.

I'm going to merge #1181 soon so update your branch and then run the command I mentioned above and check if the messages got updated 😄 👍

**Pull request closed without merging**
