### PR TITLE
add message reactions

### PR DESCRIPTION
**Pull request by anxodio**
# Description

This PR add reaction capabilities to opsdroid, adding a new `react` method in `Message` and `Connector`.

By default it just log a debug message and return False, but can be implemented by connectors that have react capabilities (like Slack or Github).

**Fixes** #442

## Status
**READY**

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

(By now it will be documented in the Slack connector, because it will be the only one that implements it)

# How Has This Been Tested?

I tested and checked that the new `react` methods returns False as expected.

# Checklist:

- [X] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation (if applicable)
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
This looks great!

You're missing a test for the case there `thinking-delay` is set in the config. As there is no else statement you could always just add it to the config on the connector in `test_react()`.

**Comment by anxodio** [comment]
Sorry, but i'm not sure of where to put this in the documentation. As I writed:
> (By now it will be documented in the Slack connector, because it will be the only one that implements it)

And the documentation is in the other PR: https://github.com/opsdroid/connector-slack/pull/10 

So, if we have to add it here, where you would add it?

**Comment by FabioRosado** [comment]
Since this is a new method of the connector class I think the right place for it would be in the [connector documentation](http://opsdroid.readthedocs.io/en/stable/extending/connectors/)

Hope this helps 👍

**Comment by jacobtomlinson** [comment]
Awesome many thanks!

**Pull request merged**
