### PR TITLE
If env HTTPS_PROXY/HTTP_PROXY is configured, slack event resp now respects proxy config

### PR DESCRIPTION
**Pull request by rodrigo-albuquerque**
# Description

Fairly simple. I was testing opsdroid behind a proxy with HTTP_PROXY/HTTPS_PROXY configured and it was timing out.

Added trust_env=True to aiohttp.ClientSession and it solved the problem.

Reference: https://docs.aiohttp.org/en/stable/client_reference.html

### CODE REVIEW

**Review by jacobtomlinson — COMMENTED** [review]
Thanks this seems great. Is there a way we can construct a simple test to ensure that this continues to work in the future?

**Comment by rodrigo-albuquerque** [comment]
I'm not sure if I understand your question. You mean trust_env?

If so, `aiohttp.helpers` can confirm whether `trust_env` picked up the proxy or not:

```python
>>> import aiohttp
>>> helpers = aiohttp.helpers.proxies_from_env()
>>> helpers
{'https': ProxyInfo(proxy=URL('http://myproxy:8080'), proxy_auth=None), 'http': ProxyInfo(proxy=URL('http://myproxy:8080'), proxy_auth=None)}
>>>
```

if no proxy is picked up, helpers should be an empty dict {}.

**Comment by jacobtomlinson** [comment]
I mean can we test that opsdroid works with a proxy? What I want to avoid is the `trust_env` accidentally getting removed in the future during a refactor and this functionality breaking again. We should add a test to avoid regressions here.

This would probably involve a small fixture that starts a proxy in a new process and temporarily configures `HTTP(S)_PROXY`. Then asserts that requests were successfully sent via the proxy.

**Comment by rodrigo-albuquerque** [comment]
Oh, I think I've got, like a test_slack_connector_proxy.py right?

**Pull request closed without merging**
