### PR TITLE
Do not parse own messages in Mattermost connector

### LINKED ISSUE #1775: Infinite self-responses in Mattermost connector
After fixing the Mattermost connector with PR #1774 it turns out it suffers from the same infinite self-response problem  (#1691) as was fixed for the Gitter connector in #1692.

### PR DESCRIPTION
**Pull request by davdr**
# Description

Fixes #1775 

Includes PR #1774 because it's a prerequisite for being able to use Mattermost in the first place (branched this fix off the former fix).

## Status
**READY**

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- Tested manually

I haven't had the time to dive into Opsdroid unit testing approach and workflow unfortunately.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by FabioRosado** [comment]
Oooff... I think I broke this when It tried to fix the merge conflict 😢

**Comment by davdr** [comment]
@FabioRosado should be fixed now.

**Comment by davdr** [comment]
I've slightly changed the logic to make sure a message is also parsed when the bot id is unknown for some reason. This fixes the unit test failure.

At least locally I still have an assertion error in `tests/test_events.py::TestVideo::test_video` but that's unrelated to this PR and was already the case on master without my changes.

**Review by FabioRosado — APPROVED** [review]
Thank you again for working on this and for fixing my bad merge 😬 

That test will fail locally if you don't have ffmpeg installed locally, everything is passing but the docs so I'm merging this PR now 👍

**Comment by davdr** [comment]
@FabioRosado thanks for merging -- you beat me to it, I just added a unit test to verify the new behaviour :-)

**Comment by FabioRosado** [comment]
Oops apologies for that Feel free to create a new PR with the test 😄

**Comment by davdr** [comment]
No apologies needed, it's me who should've done that earlier :-) New PR on the way.

**Pull request merged**
