### PR TITLE
Support custom webhook response

### PR DESCRIPTION
**Pull request by cupen**
# Description
sometimes, we need to respond a custom json or text to the webhook caller. 
let me know what do you think about this. I'll add or run testcase later.

## Status
**UNDER DEVELOPMENT**

## Type of change
- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

# Checklist:
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Awesome! This is really useful, thanks for raising this. Please go ahead with tests and documentation.

**Comment by cupen** [comment]
OK. I'll do it.

**Comment by jacobtomlinson** [comment]
I've gone ahead and added the tests and docs, I totally understand that things sometimes get in the way of updating a PR you've raised. It has now been merged in #807 so I'm going to close this PR.

Thanks for your help! Ping me your address via DM on [Twitter](https://twitter.com/_jacobtomlinson) or [Gitter](https://gitter.im/opsdroid) and I'll post you some [opsdroid stickers](https://medium.com/opsdroid/stickers-for-contributors-a0a1f9c30ec1)!

**Comment by cupen** [comment]
Nice work!   sorry for my procratinating.

**Pull request closed without merging**
