### PR TITLE
Create mastodon connector

### PR DESCRIPTION
**Pull request by jacobtomlinson**
# Description

Started playing around with a Mastodon connector given all the folks heading there lately.

## Status
**READY**

## Type of change

New connector

# How Has This Been Tested?

Added tests and also tries it out [with a demo account](https://botsin.space/web/@opsdroiddev).

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by Cadair — APPROVED** [review]
Looks sane to me, though the windows CI is angry?

**Comment by jacobtomlinson** [comment]
Yeah I haven't had time to dig into this yet. This Windows CI just seems to hand when collecting tests. I wonder if `mastodon.py` does weird stuff on Windows or something.

**Comment by xloem** [comment]
This is what I got. First time I've ever used Powershell. I'm noting that the tests construct ExternalAPIMockServer twice.
```
FAILED opsdroid/connector/mastodon/tests/test_mastodon.py::test_image_sent - PermissionError: [Errno 13] Permission denied: 'C:\\Users\\user\\AppData\\Local\\Temp\\tmpgavx01hh'
FAILED opsdroid/connector/mastodon/tests/test_mastodon.py::test_toot_sent - OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8089): only one usage of each socket...
ERROR opsdroid/connector/matrix/tests/test_connector_connect.py::test_connect_access_token - OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8089): only one usage of each socket...
========== 2 failed, 745 passed, 1 skipped, 7 xfailed, 1 xpassed, 452 warnings, 1 error in 404.57s (0:06:44) ========== 
```

**Comment by xloem** [comment]
The results of my exploration around this PR were that a fix appears required in mastodon's dependency specification for these tests to pass reliably. I've submitted the fix to them at https://github.com/halcy/Mastodon.py/pull/317 . I have a draft fork of this PR with all tests passing at https://github.com/xloem/opsdroid/pull/1, but it at this time of writing it references my Mastodon.py pull request as a direct dependency.

**Comment by jacobtomlinson** [comment]
Closing as super stale

**Pull request closed without merging**
