### PR TITLE
[UNDER DEVELOPMENT]Connector twitter

### PR DESCRIPTION
**Pull request by Razi007**
# Description

Fixes #<issue>

## Status
**READY** | **UNDER DEVELOPMENT** | **ON HOLD**

## Type of change

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- This change requires a documentation update
- Documentation (fix or adds documentation)

# How Has This Been Tested?

- Test A
- Test B

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Razi007** [comment]
@jacobtomlinson  getting error while runnig tox on this branch could you please help!!
`gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -Ireppy/rep-cpp/include -Ireppy/rep-cpp/deps/url-cpp/include -I/anaconda3/include/python3.7m -c reppy/rep-cpp/src/agent.cpp -o build/temp.macosx-10.7-x86_64-3.7/reppy/rep-cpp/src/agent.o -std=c++11
  In file included from reppy/rep-cpp/src/agent.cpp:5:
  reppy/rep-cpp/deps/url-cpp/include/url.h:8:10: fatal error: 'unordered_map' file not found
  #include <unordered_map>
           ^~~~~~~~~~~~~~~
  1 error generated.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for reppy
  Running setup.py clean for reppy
Failed to build reppy`

**Comment by Razi007** [comment]
> ## @jacobtomlinson / @FabioRosado getting error while runnig tox on this branch could you please help!!
> `gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/anaconda3/include -arch x86_64 -I/anaconda3/include -arch x86_64 -Ireppy/rep-cpp/include -Ireppy/rep-cpp/deps/url-cpp/include -I/anaconda3/include/python3.7m -c reppy/rep-cpp/src/agent.cpp -o build/temp.macosx-10.7-x86_64-3.7/reppy/rep-cpp/src/agent.o -std=c++11
> In file included from reppy/rep-cpp/src/agent.cpp:5:
> reppy/rep-cpp/deps/url-cpp/include/url.h:8:10: fatal error: 'unordered_map' file not found
> #include <unordered_map>
> ^~~~~~~~~~~~~~~
> 1 error generated.
> error: command 'gcc' failed with exit status 1
> ERROR: Failed building wheel for reppy
> Running setup.py clean for reppy
> Failed to build reppy`

able to run tox using `CFLAGS=-stdlib=libc++`

**Comment by FabioRosado** [comment]
Are you using windows? Never came across that issue

**Comment by FabioRosado** [comment]
Closing this PR since its been a while since it had any activity

**Pull request closed without merging**
