### PR TITLE
Fixing rasanlu parser : dict object has no attribute matchers issue #860

### LINKED ISSUE #860: rasanlu parser : dict object has no attribute matchers
Hi all,

# Description
When using rasanlu parser with no intents file (no need to train the module, already done) an attribute issue error happened in function **_get_all_intents(skills)**

```
...
    matchers = [matcher for skill in skills for matcher in skill.matchers]
  File "/Users/IOBreaker/Developments/Bots/opsdroid/opsdroid/parsers/rasanlu.py", line 19, in <listcomp>
    matchers = [matcher for skill in skills for matcher in skill.matchers]
AttributeError: 'dict' object has no attribute 'matchers'
```
## Steps to Reproduce
1- create or use a skill that respond to an intent
2- use rasanlu as a parser
3- do not provide an intent file to opsdroid train your model outside of opsdroid
4- start opsdroid

## Expected Functionality
if no intent provided, not training step should be issued (no crash)

## Experienced Functionality

issue error happened in function **_get_all_intents(skills)**

```
INFO opsdroid.parsers.rasanlu: Starting Rasa NLU training.
DEBUG asyncio: Using selector: KqueueSelector
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/IOBreaker/Developments/Bots/opsdroid/opsdroid/__main__.py", line 206, in <module>
    init()
  File "/Users/IOBreaker/Developments/Bots/opsdroid/opsdroid/__main__.py", line 203, in init
    main()
  File "/Users/IOBreaker/Developments/Bots/opsdroid/venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/IOBreaker/Developments/Bots/opsdroid/venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/IOBreaker/Developments/Bots/opsdroid/venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/IOBreaker/Developments/Bots/opsdroid/venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/IOBreaker/Developments/Bots/opsdroid/opsdroid/__main__.py", line 196, in main
    opsdroid.load()
  File "/Users/IOBreaker/Developments/Bots/opsdroid/opsdroid/core.py", line 152, in load
    self.train_parsers(self.modules["skills"])
  File "/Users/IOBreaker/Developments/Bots/opsdroid/opsdroid/core.py", line 270, in train_parsers
    asyncio.gather(*tasks, loop=self.eventloop))
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/Users/IOBreaker/Developments/Bots/opsdroid/opsdroid/parsers/rasanlu.py", line 87, in train_rasanlu
    intents = await _get_all_intents(skills)
  File "/Users/IOBreaker/Developments/Bots/opsdroid/opsdroid/parsers/rasanlu.py", line 19, in _get_all_intents
    matchers = [matcher for skill in skills for matcher in skill.matchers]
  File "/Users/IOBreaker/Developments/Bots/opsdroid/opsdroid/parsers/rasanlu.py", line 19, in <listcomp>
    matchers = [matcher for skill in skills for matcher in skill.matchers]
AttributeError: 'dict' object has no attribute 'matchers'
```

This error is due to this line :
> matchers = [matcher for skill in skills for matcher in skill.matchers]

Exeample of 3 skills used with rasanlu parser :

```
[
{'module': <module 'opsdroid-modules.skill.discussion' from '/Users/IOBreaker/Library/Application Support/opsdroid/opsdroid-modules/skill/discussion/__init__.py'>, 'config': {'name': 'discussion', 'path': '/Users/IOBreaker/Developments/Bots/opsdroid-data/skills/skill-rasanlu-discussion', 'debug': False, 'no-cache': True, 'module': '', 'type': 'skill', 'is_builtin': None, 'entrypoint': None, 'module_path': 'opsdroid-modules.skill.discussion', 'install_path': '/Users/IOBreaker/Library/Application Support/opsdroid/opsdroid-modules/skill/discussion', 'branch': 'master'}, 'intents': None}, 

{'module': <module 'opsdroid-modules.skill.hyperv' from '/Users/IOBreaker/Library/Application Support/opsdroid/opsdroid-modules/skill/hyperv/__init__.py'>, 'config': {'name': 'hyperv', 'path': '/Users/IOBreaker/Developments/Bots/opsdroid-data/skills/skill-rasanlu-hyperv', 'apixu-key': 'ee6eef66ee4e4ee3aee64539192002', 'debug': False, 'no-cache': True, 'module': '', 'type': 'skill', 'is_builtin': None, 'entrypoint': None, 'module_path': 'opsdroid-modules.skill.hyperv', 'install_path': '/Users/IOBreaker/Library/Application Support/opsdroid/opsdroid-modules/skill/hyperv', 'branch': 'master'}, 'intents': None},

 {'module': <module 'opsdroid-modules.skill.vmware' from '/Users/IOBreaker/Library/Application Support/opsdroid/opsdroid-modules/skill/vmware/__init__.py'>, 'config': {'name': 'vmware', 'path': '/Users/IOBreaker/Developments/Bots/opsdroid-data/skills/skill-vmware', 'no-cache': True, 'module': '', 'type': 'skill', 'is_builtin': None, 'entrypoint': None, 'module_path': 'opsdroid-modules.skill.vmware', 'install_path': '/Users/IOBreaker/Library/Application Support/opsdroid/opsdroid-modules/skill/vmware', 'branch': 'master'}, 'intents': None}
 ]
```

## Versions
- **Opsdroid version: v0.14.1+19.g6360912**
- **Python version: 3.7.0**

## Configuration File

```
parsers:
#  ## Rasanlu (http://opsdroid.readthedocs.io/en/stable/matchers/rasanlu)
  - name: rasanlu
    url: http://localhost:5000
    project: myProject
    model: myModule
    min-score: 0.8

skills:
  - name: social
    path: /Users/IOBreaker/Developments/Bots/opsdroid-data/skills/skill-rasanlu-vmware
    debug: true
    no-cache: true

```

### PR DESCRIPTION
**Pull request by iobreaker**
# Description

When using rasanlu parser with no intents file (no need to train the module, already done) an attribute issue error happened in function _get_all_intents(skills)

...
    matchers = [matcher for skill in skills for matcher in skill.matchers]
  File "/Users/IOBreaker/Developments/Bots/opsdroid/opsdroid/parsers/rasanlu.py", line 19, in <listcomp>
    matchers = [matcher for skill in skills for matcher in skill.matchers]
AttributeError: 'dict' object has no attribute 'matchers'

Fixes #860

After discussion with @jacobtomlinson the decision  was to go using intents provided directly by the skill dict.

Beside, an other correction was added to this fixes according to [rasa_nlu](https://github.com/RasaHQ/rasa_nlu/blob/master/docs/http.rst#post-train) documentation

```
The request should always be sent as application/x-yml regardless of wether you use json or md for the data format. Do not send json as application/json for example.
```

## Status
**READY** | **~UNDER DEVELOPMENT~** | **~ON HOLD~**

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I tested the fix on my environment, no issue detected

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works (test file modification)
- [x] New and existing unit tests pass locally with my changes
- [x] Tox ok

### CODE REVIEW

**Comment by iobreaker** [comment]
I did some other tests about Content Type and bellow what i've got as results :

### Test 1

- Content-Type : Application/x-yml
- file type : intents.md
- File Content :

```yaml
## intent:user_say_iam_back
i am back
i am back again
back again
```

- Result

```json
{
  "error": "Content-Type must be 'application/x-yml' or 'application/json'"
}
```


### Test 2

- Content-Type : Application/json
- file type : intents.json
- File Content :


```json
{
	"rasa_nlu_data": {
		"regex_features": [

		],
		"entity_synonyms": [

		],
		"common_examples": [
			{
				"text": "i am back",
				"intent": "user_is_back",
				"entities": [

				]
			},
			{
				"text": "i am back again",
				"intent": "user_is_back",
				"entities": [

				]
			},
			{
				"text": "back again",
				"intent": "user_is_back",
				"entities": [

				]
			}
		]
	}
}
```

- Result

```json
{
  "info": "new model trained",
  "model": "ergo"
}

```

I'd like to have your feedback about that please

Regards

**Comment by iobreaker** [comment]
I founded why we have this behaviours. As you can check  [here](https://github.com/RasaHQ/rasa_nlu/blob/master/sample_configs/config_train_server_md.yml) in RasaHQ github docs, the file format has changed.

So i changed the intents.md file format and the training was successful


- Content-Type : Application/x-yml
- File type : intents.md
- File Content :

```yaml
language: "en"
pipeline: "spacy_sklearn"
# data contains the same md, as described in the training data section
data: |
  ## intent:user_say_iam_back
  - i am back
  - i am back again
  - back again
```

- Opsdroid side

```
INFO opsdroid.parsers.rasanlu: Starting Rasa NLU training.
INFO opsdroid.parsers.rasanlu: Now training the model. This may take a while...
INFO opsdroid.parsers.rasanlu: Rasa NLU training completed in 0 seconds.
INFO opsdroid.parsers.rasanlu: Initialising Rasa NLU model.
DEBUG opsdroid.parsers.rasanlu: Rasa NLU response - {"intent": {"name": null, "confidence": 0.0}, "entities": [], "text": "", "project": "ergo", "model": "model_20190320-144251"}
INFO opsdroid.parsers.rasanlu: Initialisation complete in 1 seconds.
DEBUG opsdroid.connector.websocket: Starting Websocket connector
DEBUG opsdroid.connector.telegram: Loaded telegram connector
```

- Rasanlu server side result 

```
2019-03-20 14:42:50+0100 [-] "127.0.0.1" - - [20/Mar/2019:13:42:50 +0000] "GET /status HTTP/1.1" 200 459 "-" "Python/3.7 aiohttp/3.5.4"
2019-03-20 14:42:50+0100 [-] 2019-03-20 14:42:50 DEBUG    rasa_nlu.data_router  - New training queued
2019-03-20 14:42:51+0100 [-] "127.0.0.1" - - [20/Mar/2019:13:42:51 +0000] "POST /train?project=ergo&fixed_model_name=326346356235623562356fdgsdfbgdf324562362356&token=ed6ahthogeexoonahL7gof1maGh1EiSDF5Hi8sd HTTP/1.1" 200 69 "-" "Python/3.7 aiohttp/3.5.4"
2019-03-20 14:42:52+0100 [-] 2019-03-20 14:42:52 INFO     rasa_nlu.components  - Added 'nlp_spacy' to component cache. Key 'nlp_spacy-en'.
2019-03-20 14:42:52+0100 [-] "127.0.0.1" - - [20/Mar/2019:13:42:52 +0000] "POST /parse HTTP/1.1" 200 150 "-" "Python/3.7 aiohttp/3.5.4"
```

- Response :

```
{
  "info": "new model trained",
  "model": "ergo"
}
```

Please can you check from your side and confirm

Next step if it's confirmed is to update the rasanlu.md documentation (about intents.md gived example).

A good thing will be adding json support (nice to have)

Regards

**Comment by jacobtomlinson** [comment]
This looks great. It's a shame that rasa have broken the format upstream, but I feel like their move to yaml/json is probably a good one. 

We should probably modify the code to stop looking for `intents.md` and instead look for `intents.yaml`, `intents.yml` or `intents.json`. This would mean we can support all the formats above.

Would you be happy to make this change here?

**Comment by iobreaker** [comment]
It would be great to support json and yaml intent files.

I am going to change the **def _load_intents(config)** in **loader.py**  function to load **intents.yml** instead of **intents.md** and modify the corresponding docs to indicate the new why to implement the intent file. This will allow us to close the ongoing issue.

When it's done, why not working on json, yml, yaml support :-)

**Comment by iobreaker** [comment]
I changed as discussed the code to manage intents.yml file in loader and tests files.
I updated the doc to reflct the new intents.yml file format.
can you please check

**Comment by jhofeditz** [comment]
@iobreaker I am also testing rasa with opsdroid and cloned your repo to test. I just installed the latest Rasa NLU and the API /train endpoint is returning zip content 
https://github.com/RasaHQ/rasa_nlu/blob/master/rasa/nlu/server.py#L277
This makes training fail:
> aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: application/zip'
I only picked up opsdroid today and rasa yesterday, so I might be missing something...

**Comment by iobreaker** [comment]
Hi @jhofeditz,

can you please explain exactly how are you using opsdroid with rasanlu
- The content of your intents.yml
- The cli you are using to start rasa server
- The debug log from opsdroid

Thx

**Comment by jhofeditz** [comment]
ah, I was using the `rasa/rasa_nlu:latest-spacy` docker image. When I switch to `0.14.4-spacy` (or `pip install rasa-nlu`) I get the expected yml output. 

So, it's either a breaking change in 0.15 or a bug.

**Comment by FabioRosado** [comment]
Thank you for working on this issue @iobreaker, I am a bit worried about the breaking change of the future versions of rasa nlu, but this is something we will have to tackle when they release the next version.

Jacob seems to be happy with the PR as well so I am going to merge it now to master 😄 👍

**Comment by iobreaker** [comment]
@jhofeditz can you please log an issue and describe exactly how to reproduce it (env, cli, config ...)

@FabioRosado because opsdroid is an opensource project with no commitments about releases (best efforts) i think a best practices will be :

- Indicate in the documentation which versions opsdroid support for each external module or parser ...
- For each code that need to address an external resources, a check of supported version should be done by the developer to avoid crashes or a bad behaviors.

**Pull request merged**
