### PR TITLE
WIP Events IIc - Slack

### PR DESCRIPTION
**Pull request by SolarDrew**
# Description

Follows from PRs #951 and #1069. Adds Slack-specific event types and appropriate handling by the connector.

Requires #1069.

## Status
**UNDER DEVELOPMENT**

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

# How Has This Been Tested?

It hasn't yet.

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Is this orthogonal to #1070 or is a dependant on anything in there?

Also I guess we need some changes here after #1081.

**Comment by Cadair** [comment]
I think it should be mostly orthogonal to #1070 but a few of the event classes might be needed in both.

**Comment by Cadair** [comment]
Stop shaming us stale bot :stuck_out_tongue:

**Comment by Cadair** [comment]
This now very much needs a rebase.

**Pull request closed without merging**
