### PR TITLE
Avoiding hard coded module version in requirement.txt

### PR DESCRIPTION
**Pull request by apointeau**
Small improvement to allow having more recent version of the modules listed in the requirements.txt

### CODE REVIEW

**Comment by go8ose** [comment]
I'm going to go out on a limb here(1), and suggest that pinning the requirements to specific versions is best practice, and this PR will get turned down.  Jacob has the pyup bot setup to suggest PR's to update dependancies automatically (#350 is one example of that), so these requirements regularly get updated anyway.

(1) It's a limb for me, I'm not a python expert

**Comment by go8ose** [comment]
Oh, and thanks for the PR as well!

I'm sure if @FabioRosado had responded first, he would have been a lot more graceful about this.  I'm sorry about that. Please hang around though, we'd love to here from you again.

**Comment by jacobtomlinson** [comment]
Thanks for raising this. Sadly as @go8ose points out the pinned versions are intentional as it helps provide a consistent environment for opsdroid. To avoid any collisions with other libraries it is recommend you use Python virtual environments.

**Comment by apointeau** [comment]
No problem guys, I understand your point of view fully ! :-)
You know, it's possible to limit the maximum version to keep the environment consistent.

For example :
    mypackage>=1.0,<=2.0

In general, if you limit to the a specific major version, you keep the backward compatibility.

**Comment by jacobtomlinson** [comment]
I agree with your point. 

This project uses pyup.io to run unit tests whenever a new dependency update is released. This is really helpful for finding issues caused by new releases (SemVer isn't perfect if other developers don't follow it well). 

The other argument could be to pin in the `requirements.txt` but be flexible in the `setup.py` for releases. I would be interested in @pelson's thoughts.

**Comment by apointeau** [comment]
I'm new in the contribution world, thank you for the explanation, it seems legit now.
I find your project by http://up-for-grabs.net

**Comment by jacobtomlinson** [comment]
Welcome to open source contributing! It's great to have you here. 

Ping me your address via DM on [Twitter](https://twitter.com/_jacobtomlinson) or [Gitter](https://gitter.im/opsdroid) and I'll post you some [opsdroid stickers](https://medium.com/opsdroid/stickers-for-contributors-a0a1f9c30ec1)!

**Comment by pelson** [comment]
> The other argument could be to pin in the requirements.txt but be flexible in the setup.py for releases.

Definitely support that. https://github.com/opsdroid/opsdroid/blob/master/setup.py#L13 states:

> For now we simply define the install_requires based on the contents of requirements.txt. In the future, install_requires may become much looser than the (automatically) resolved requirements.txt.

The relevant Python docs for this are at https://packaging.python.org/discussions/install-requires-vs-requirements/.

**Pull request closed without merging**
