### PR TITLE
Migrate test_matchers.py to pytest

### LINKED ISSUE #1502: Migrate tests from unittest to pytest
Our existing test suite has been written with the Python [`unittest`](https://docs.python.org/3/library/unittest.html) framework. However, as the test suite has grown and opsdroid has become more complex we are running into issues with the tests. Mainly around setting up and tearing down tests.

The @opsdroid/maintainers team have decided that we want to migrate all tests to be written with the [`pytest`](https://docs.pytest.org/en/latest/contents.html) framework instead so that we can make better use of fixtures. Fixtures are more reusable and portable and should help reduce complexity all over.

There's a lot to be done but it can be done piece by piece as `pytest` can run tests in either format. So if you wish to help in the effort you can start by searching the codebase for unittest suites. These are classes which are subclassed from `unittest.TestCase` or `asynctest.TestCase`, so searching all files for `unittest.TestCase` and `asynctest.TestCase` should be a good place to start.

For detailed information on running the test suite and contributing to opsdroid [see the docs](https://docs.opsdroid.dev/en/latest/contributing/index.html). But the quickest way to get started us with [`tox`](https://tox.readthedocs.io/en/latest/).

```bash
pip install -U tox  # You only need to install tox once

tox -e py36,lint  # Run the Python 3.6 tests (the lowest version we support) and the linter
```

Once you have found a test suite you wish to convert there are a few steps you need to follow to convert from unittest to pytest:
- Move tests from top level `tests` directory to a nested `tests` directory in opsdroid. Create one in an appropriate place if there isn't already one.
- Remove test from class, pytest tests are just regular functions.
- Change assertions to use regular `assert` or [pytest assertions](https://docs.pytest.org/en/latest/assert.html).
- Mark async tests. In unittest we write async tests by using the `asynctest.TestCase`, but in pytest we decorate our tests with `@pytest.mark.asyncio` instead.
- Move setup operations to fixtures. If a test class contains a `setUp` method anything created here should become a fixture. Check the existing fixtures in `conftest.py` before creating new ones.
- Add docstrings to tests and fixtures to explain what they do. We have been pretty rubbish with this up until now and there are many tests which are not obvious in what they are testing.

Here's an example:

```python
# Before (unittest)
import asynctest
import asynctest.mock as mock

from opsdroid.cli.start import configure_lang
from opsdroid.core import OpsDroid
from opsdroid.events import Message
from opsdroid.matchers import match_regex
from opsdroid import constraints


class TestConstraints(asynctest.TestCase):
    """Test the opsdroid constraint decorators."""

    async def setUp(self):
        configure_lang({})

    async def getMockSkill(self):
        async def mockedskill(opsdroid, config, message):
            pass

        mockedskill.config = {}
        return mockedskill

    async def test_constrain_rooms_constrains(self):
        with OpsDroid() as opsdroid:
            skill = await self.getMockSkill()
            skill = match_regex(r".*")(skill)
            skill = constraints.constrain_rooms(["#general"])(skill)
            opsdroid.skills.append(skill)

            tasks = await opsdroid.parse(
                Message(text="Hello", user="user", target="#random", connector=None)
            )
            self.assertEqual(len(tasks), 2)  # Just match_always and match_event
```

```python
# After (pytest)
import pytest

from opsdroid.cli.start import configure_lang
from opsdroid.core import OpsDroid
from opsdroid.events import Message
from opsdroid.matchers import match_regex
from opsdroid import constraints


configure_lang({})  # Required for our internationalization of error messages


@pytest.fixture
def opsdroid():
    """An instance of the OpsDroid class."""
    with OpsDroid() as opsdroid:
        yield opsdroid


@pytest.fixture
def mock_skill():
    """A skill which does nothing but follows the skill API."""

    async def mockedskill(opsdroid, config, message):
        pass

    mockedskill.config = {}
    return mockedskill


@pytest.mark.asyncio
async def test_constrain_rooms_constrains(opsdroid, mock_skill):
    """Test that with the room constraint a skill is not called."""
    skill = match_regex(r".*")(mock_skill)
    skill = constraints.constrain_rooms(["#general"])(skill)
    opsdroid.skills.append(skill)

    tasks = await opsdroid.parse(
        Message(text="Hello", user="user", target="#random", connector=None)
    )
    assert len(tasks) == 2  # Just match_always and match_event
```

Fixtures such as the `opsdroid` fixture will be extremely useful in many tests, so we will be creating some standard ones like this which will be available in all tests. If you write a fixture that you think could be useful in other places please don't hesitate to contribute it to the `conftest.py` file.

If you have any questions you can chat to us on [Matrix](https://riot.im/app/#/room/#opsdroid-general:matrix.org). We encourage you to get started and if you have issues or get stuck then open a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) with your changes and we can take a look.

---

When this issue is complete the documentation about the migration should be removed from the testing docs.

### PR DESCRIPTION
**Pull request by tardigrde**
# Description

Migrating test_matchers.py to pytest.

Fixes #1502 

## Status
**READY**

## Type of change

Test

# How Has This Been Tested?

With pytest on local machine.

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by tardigrde** [comment]
A little bit of help needed.

The test has these mocked async functions, that return another function. One of them is `get_mock_skill` right in the beginning of the file. I have tried to move these under a pytest.fixture, but then it is required to put the 3 input parameters `opsdroid, config, message` in the function calls (e.g. at test_matchers.py:35 -> `opsdroid.skills.append(decorator(await get_mock_skill()))`, the function call would need 3 input parameters). Should they be even fixtures? I don't think so, because they are not results we are asserting to, but utility functions for the tests.

If these mocked async functions are okay the way they are, then this is ready for a code review.

**Review by FabioRosado — APPROVED** [review]
Hello @tardigrde  thank you for working on this issue.

I guess a way to do it would be passing the opsdroid fixture to `get_mock_skill` and a config dict for the `config` parameter and then a Message event for the message parameter.

I'm not sure if it will matter much on this case to be honest and seems that what you have done is still working and following the same pattern of the unittests so it's probably fine.

**Comment by tardigrde** [comment]
Okay, then I would mark this as ready for review, if the above mentioned thing is not a problem.

**Comment by FabioRosado** [comment]
Thanks again for working on this it's now merged 😁

**Pull request merged**
