### PR TITLE
Adding Gitter info in docs.extending

### LINKED ISSUE #321: Add more references to the Gitter group in the docs
# Description
Add more references and links to the [Gitter group](https://gitter.im/opsdroid) throughout the documentation. This will help users and contributors stay more involved in the opsdroid community.

Resulting from #317.

### PR DESCRIPTION
**Pull request by adityac8**
# Description

I have updated the files in the **extending** folder. I have added the link to Gitter group at the end of each file.
Fixes #321 

## Status
**READY**

## Type of change

- Documentation (fix or adds documentation)

# How Has This Been Tested?

I have opened each `README` file in GitHub to see if it is rendered properly.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
Replaces #507.

Thanks for this! I would like to see the message also on the issue template, the contributing guidelines, and the tutorials. Would you be able to add it?

**Comment by adityac8** [comment]
Hey @jacobtomlinson 
> issue template, the contributing guidelines, and the tutorials.

I'm on it!

**Comment by adityac8** [comment]
Hey, @jacobtomlinson I have updated the files. I don't suggest adding **Gitter** links to the `issue template`. What do you think?

**Comment by jacobtomlinson** [comment]
Why do you not suggest adding it there?

**Comment by adityac8** [comment]
I suppose, the users will definitely have a look at the other pages and might find a bug for which they want to raise an issue. They would have already gone past a page that has a link for Gitter. Also, as the **Issue template** gets rendered, the link for Gitter would also be shown in every issue which increases redundancy.

**Comment by jacobtomlinson** [comment]
I don't agree that they will have been to gitter. They might have a problem and are unsure whether they should raise an issue or not. So having a comment in the issue template might lead them to actually just post on gitter.

You can include HTML comments in the issue template which you will see when creating the issue but are hidden when the issue is rendered.

`<!-- this is a hidden comment -->`

**Comment by adityac8** [comment]
The hidden comment would be great. I'm on it! 👍

**Comment by jacobtomlinson** [comment]
Thanks for this!

Ping me your address via DM on [Twitter](https://twitter.com/_jacobtomlinson) or [Gitter](https://gitter.im/opsdroid) and I'll post you some [opsdroid stickers](https://medium.com/opsdroid/stickers-for-contributors-a0a1f9c30ec1)!

**Pull request merged**
