### PR TITLE
added google style docstring

### PR DESCRIPTION
**Pull request by mraza007**
# Description

Adding google style docstrings. I hope I added the right style guide I was having a hard time reading about function it already has docstrings should I use that

Fixes #<issue>

## Status
**READY** | **UNDER DEVELOPMENT** | **ON HOLD**

## Type of change

_Please delete options that are not relevant._
- Documentation (fix or adds documentation)

# How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration._

- Test A
- Test B

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by mraza007** [comment]
I'll do that

**Comment by mraza007** [comment]
Hey I fixed it

**Comment by jacobtomlinson** [comment]
Thanks for this @mraza007!

As you can see this PR has been rejected by our automated testing. We can't merge it until you resolve the issues it has raised. If you click the red cross next to the failed commit you will see the problems.

To help you out it is the [linting step](https://travis-ci.org/opsdroid/opsdroid/jobs/401597207) which is failing because you have trailing whitespace on lines 28 and 29 of your docstring.

This is something your text editor should clean up for you. You may want to have a Google around to figure out how to enable this option. But to get this PR merged please delete the extra tabs/spaces at the end of those lines.

**Comment by mraza007** [comment]
will fix it

**Comment by jacobtomlinson** [comment]
I'm guessing you haven't found time to fix it @mraza007 so I've taken the liberty of doing it myself in the interest of getting this merged.

Thanks for your contribution!

**Pull request merged**
