### PR TITLE
First attempt at token auth for matrix connector

### PR DESCRIPTION
**Pull request by colonelkrud**
# Description

This will allow the user to define an authentication token in the config for the matrix connector instead of the username and password. This should simplify some situations where the matrix homeserver considers each login as a new device and provide users with a method of revoking authentication to a user without changing their credentials.

Fixes n/a

## Status
**READY**

## Type of change

- New feature (non-breaking change which adds functionality)
- This change requires a documentation update

# How Has This Been Tested?

- Removed password from config file and tested login with token for two separate users. (need to run actual tests)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by Cadair** [comment]
Looks good to me. You could add a unit test that checks login isn't called if a token is provided.

The only other thing that might be worth doing is checking what happens if the token is invalid.

**Comment by oleg-fiksel** [comment]
Works for me with the following config:

```
connectors:
  - name: matrix
    mxid: "@testuser:mymatrixdomain.com"
    token: "**********************************************"
    homeserver: "https://my-matrix.server.com"

## Configure the web server
web:
  host: '0.0.0.0'
  port: 8080

parsers:
  - name: dialogflow
    access-token: "*******************"

skills:
  - name: dialogflow-test
    path: /skills/dialogflow-test
```

**Comment by colonelkrud** [comment]
Yep. It’s been working on my bridge as well. Just need to update the matrix connector test file to check for a few things but I’ve been away for a bit. If someone wants to take a shot at the tests, I’ll gladly merge them :p 

Also need to make sure the docs are all up to date. I think I got them all but there might be a default config that needs to be updated.

**Comment by FabioRosado** [comment]
Hey guys is it possible to get my PR merged so we update this one and we can merge is issue soon? Thanks 😄

**Pull request closed without merging**
