### PR TITLE
Fix reload

### PR DESCRIPTION
**Pull request by redfruitt**
# Description

Fixes the buggy reload feature which does not work consistently.

**Fixes** #413 

## Status
**READY** 

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by FabioRosado** [comment]
Thanks for working on this @redfruitt your travis failed due to linting issues - unused import can you check that out?

Also, could you remove the file `tox-generated.ini` from the PR?

Let me know if you need further help on these issues.

**Comment by jacobtomlinson** [comment]
This is great! I'll do some proper testing of this later and then merge!

**Comment by FabioRosado** [comment]
Just wanted to check in with you @redfruitt to see if you had the opportunity to check the missing tests and if you need any help on increasing the coverage. I've also updated this branch so everything should be up-to-date with the opsdroid master branch 👍

**Comment by redfruitt** [comment]
Hey, I'll look into this today

**Comment by FabioRosado** [comment]
@redfruitt Thanks a lot for working on this! I've just merged it into opsdroid main branch 👍

**Pull request merged**
