### PR TITLE
Experiment with Events as dataclasses

### PR DESCRIPTION
**Pull request by Cadair**
Seems to mostly work. Had to do some hacks to maintain API.

The largest advantage of this that I can see is `__repr__` and `__eq__` now "do the right thing"

### CODE REVIEW

**Comment by Cadair** [comment]
I would like to try and use this to improve the documentation generation, i.e. pulling the types (and maybe the descriptions) from the annotations.

**Comment by jacobtomlinson** [comment]
Sure! I generally want to move documentation from the markdown files into docstrings and other automatic generation tools.

If we can get the markdown bare bones enough (mostly directives within `eval_rst` blocks) then I may support switching the whole lot to rst 😉.

**Comment by Cadair** [comment]
I tired to use the typehints autodoc plugin and it all fell apart so might be swapping `events.md` to rst out of necessity :p

**Comment by Cadair** [comment]
bad stale bot

**Comment by jacobtomlinson** [comment]
Actually I think stale bot is right. What is happening here? Is this ready? We still have linting failures.

**Comment by Cadair** [comment]
I need to do some documentation updates to make the type hints nice, and fix the linting.

**Pull request closed without merging**
