### PR TITLE
Add more references to the Gitter channel in the docs

### PR DESCRIPTION
**Pull request by musatoktas**
Adding referece regarding to Issue #321 beginning and ending of the doc.

# Description

_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change._

Fixes #<issue
Reference links to the Gitter Channel added regarding to issue #321 to increase user accessibility.
## Status
**READY** | 

## Type of change

_Please delete options that are not relevant._

- Documentation (fix or adds documentation)

# How Has This Been Tested?

_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration._

- Test A
I've clicked the links I added, and they were working fine.
- Test B

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation (if applicable)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by FabioRosado** [comment]
That's a great start thank you so much for working on this issue. 
I've just seen your question on the Issue #507 and I'm not sure if adding the reference both in the beginning and end of each doc would be the best approach - perhaps Jacob has a different opinion on this tho.

@musatoktas  What do you think is best? Your opinion is important! 😃 👍

**Comment by FabioRosado** [comment]
@musatoktas  Do you know how to add multiple commits to a single pull request from the command line? It's easier for us to merge all the commits made in one PR than to have 4 PRs related to the same issue 👍

**Comment by musatoktas** [comment]
@FabioRosado I'll check this out and continue contributing like that, sorry

**Comment by FabioRosado** [comment]
@musatoktas  It's no worries we all have to start somewhere. Do you know how to do it then? I could explain it to you and then add these steps into the documentation if you think is useful - it could help others in the future.

**Comment by FabioRosado** [comment]
I have noticed that if you edit files in github in a browser it tends to create a lot of branches and makes harder to keep them up in a single commit or PR.

Are you using windows or linux?
In windows things might be a bit different and you could use the [GitHub Desktop](https://desktop.github.com) but I haven't really use it.

If you are using a mac git comes installed already and if you are using a linux you might have git installed (if not you will need to install it from the command line - example: `sudo apt-get install git`)

Then you can open the command line, open the location where you want your opsdroid copy (I keep mine in `documents/github` folder) and run the following command:

`git clone https://github.com/musatoktas/opsdroid`

_Note: This will download your own fork of opsdroid._

Then you should create a branch with the command: `git checkout -b <name-of-branch>`
This command will both create and checkout into the new branch, so you can start working on your feature. 

Once you have something good and that you wish to save run the command: `git add <name of file>` and `git commit -m "<commit message">` you can also check which files changed with the command `git status`

Now you can add all the work you do to your local repository. When you are ready to push these changes to opsdroid you can run the command `git push --set-upstream origin <name of branch>` then you can go to github.com and create the Pull request from there.

Let me know if any of this seems too confusing and I'll go into more detail :)

**Comment by musatoktas** [comment]
I've experienced git before, but I didnt use in the real project. Next time I'll use git  🗡

**Comment by musatoktas** [comment]
By the way thank for being so polite for me as a newbie

**Comment by FabioRosado** [comment]
No problem I am still a newbie and I learn something new every day so I know how it is when you are starting something, again if you need any help let me know I’ll be happy to give you a hand 😄

**Comment by musatoktas** [comment]
Thank you so much, I'll reach you when I'm in trouble 😄

**Comment by musatoktas** [comment]
I will make these changes as soon as possible I had a car accident, I'm okey but I need fix my car.

**Comment by jacobtomlinson** [comment]
Oh dear sorry to hear that!

**Comment by adityac8** [comment]
Hey, @musatoktas have a look at this [post](https://channelcs.github.io/best-practices-in-a-collaborative-environment.html). It might help in making contributions easy.

**Comment by jacobtomlinson** [comment]
Replaced by #528

**Pull request closed without merging**
